### ISSUE TITLE
You can create a new "Сварщик" with no certificate and negative level value

### ISSUE THREAD

**Issue by KhabarlakKonstantin** [olga-jane/prizm#1000]
Steps to reproduce:
1. Go to "Настройки" -> "Сварщики" 
2. Create a new "Сварщик" with no certificate and negative level value

Expected result: error message
Actual result: "Сварщик" is successfully created & saved

**Comment by KhabarlakKonstantin** [comment]
Also you can set empty or duplicate values in settings
1. "Трубопровод" -> "Название операции"
2. "Труба"  -> "Типоразмер"

**Comment by KhabarlakKonstantin** [comment]
You can set "Настройки" -> "Проект" -> "Технические параметры" -> "Допустимый размер внешнего документа" to zero or negative value

**Comment by AleksMorozova** [comment]
already fixed - fix settings Validation #1565 and Negative value on spin edit #1592
