### ISSUE TITLE
You can disable all "Права" for every registered used

### ISSUE THREAD

**Issue by KhabarlakKonstantin** [olga-jane/prizm#1001]
Steps to reproduce:
1. Go to "Настройки" -> "Роли" 
2. Deselect all rights for every account and save

Actual result: After reopening the app you cannot change setting or create a pipe, etc.
Expected result: Error message: "There is no account with this permission enabled"

**Comment by olga-jane** [comment]
It shouldn't be able to disable First administrator.

**Comment by olga-jane** [comment]
@KhabarlakKonstantin fixed
