### ISSUE TITLE
Exeption  in "Настройки"->"Трубы" with saving data

### ISSUE THREAD

**Issue by YuliaKulinich** [olga-jane/prizm#1004]
When you enter data in all fields on tab  "Трубы" and save you cannot save but can see exeption wht text:

NHibernate.HibernateException: persistence context reported no row snapshot for [Prizm.Domain.Entity.Setup.PipeMillSizeType#7d6b6b8c-35cc-4d7b-b0da-345b69a1dab5]
   в NHibernate.Engine.StatefulPersistenceContext.GetCachedDatabaseSnapshot(EntityKey key)
   в NHibernate.Event.Default.DefaultFlushEntityEventListener.GetDatabaseSnapshot(ISessionImplementor session, IEntityPersister persister, Object id)
   в NHibernate.Event.Default.DefaultFlushEntityEventListener.DirtyCheck(FlushEntityEvent event)
   в NHibernate.Event.Default.DefaultFlushEntityEventListener.IsUpdateNecessary(FlushEntityEvent event, Boolean mightBeDirty)
   в NHibernate.Event.Default.DefaultFlushEntityEventListener.OnFlushEntity(FlushEntityEvent event)
   в NHibernate.Event.Default.AbstractFlushingEventListener.FlushEntities(FlushEvent event)
   в NHibernate.Event.Default.AbstractFlushingEventListener.FlushEverythingToExecutions(FlushEvent event)
   в NHibernate.Event.Default.DefaultFlushEventListener.OnFlush(FlushEvent event)
   в NHibernate.Impl.SessionImpl.Flush()
   в NHibernate.Transaction.AdoTransaction.Commit()
   в Prizm.Main.Forms.Settings.SettingsRepositories.Commit()
   в Prizm.Main.Forms.Settings.SaveSettingsCommand.Execute()
   в Prizm.Main.Commands.CommandInfo.SimpleButtonAttacher.btn_Click(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)
   в DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   в DevExpress.XtraEditors.BaseControl.WndProc(Message& msg)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by olga-jane** [comment]
Questionable. We do not know anything about data.

**Comment by olga-jane** [comment]
closed as not reproduced
