### ISSUE TITLE
values in "комплектующие изделия" aren`t limited

### ISSUE THREAD

**Issue by Anastasia01** [olga-jane/prizm#1018]
go to "входной контроль и строительство" -> "новое комплектующие"
you may enter string  with unlimited length  in fields "номер изделия" and "номер сертификата"

**Comment by olga-jane** [comment]
it seems "Revise Db and LengthLimit.cs and find missing constants #954" is not completely fixed.

**Comment by AleksMorozova** [comment]
fixed railcar tests #988
add missing constants at this commits
