### ISSUE TITLE
Ensure that Import and Export threads call DevExpress methods in UI thread.

### ISSUE THREAD

**Issue by alexander-dembinsky** [olga-jane/prizm#1028]
This is low priority since there are no cross-thread exceptions now. However it will be better to fix.

The problem:
When user performing import or export, new thread is created because we don't want to block UI.
However this thread can call callbacks (e.g. when conflict occurs we should show message to user).
In this situation callback will be invoked in new thread, but can access to UI components created in main thread. This can lead to CrossThreadException.
The solution would be to check in methods of ExportForm and ImportForm value of "InvokeRequired" property and call UI methods correctly.

The example is here:
http://stackoverflow.com/questions/9342747/cross-thread-exception

**Comment by olga-jane** [comment]
PRISM-8
