### ISSUE TITLE
Core Review Issues

### ISSUE THREAD

**Issue by alexander-dembinsky** [olga-jane/prizm#1035]
1) Is this class really needed?
PrizmMainProject\Common\Constants.cs

2) Consider using Path.Combine() method for all parts of path and do not use backslashes.
Directories.cs
public static string FilesToAttachFolder = Path.Combine(Directory.GetCurrentDirectory(), "Data\\Attachments\\FilesToAttach\\");
public static string TargetPath = Path.Combine(Directory.GetCurrentDirectory(), "Data\\Attachments\\");
        
public static string TargetPathForView = Path.Combine(Directory.GetCurrentDirectory(), "Data\\Attachments\\tmp\\");

3) Consider removing this class src\PrizmMainProject\Controls\BindingHelper.cs.
Looks like it was created because of bad understanding of data binding.

4) PrizmApplication/DummyData folder. Is it really needed?
5) PrizmMainProject\Forms\ExternalFile\AddExternalFileCommand.cs, PrizmMainProject\Forms\ExternalFile\DownloadFileCommand.cs, PrizmMainProject\Forms\ExternalFile\ViewFileCommand.cs

It seems we don't need to check CanExecute() inside Execute(). This is responsibility of calling code.

<pre>
public void Execute()
      
{
            
	if (CanExecute())
            
        {
 ......
        }
}
</pre>

For notifications about unavailability to execute commands, commandmanager should be enhanced to allow to consume callback for such case.

Use Path.Combine() method to concatenate parts of path correctly:
System.IO.File.Copy(Directories.FilesToAttachFolder + fileEntity.NewName, Directories.TargetPath + fileEntity.NewName);

6) To Delete?
<pre>
public enum SplashScreenCommand
        {
        }
</pre>

7) AuditInterceptor class have disposable field IAuditLogRepository so it should be disposable too.
8) AuditInterceptor is [Serializable], however currentName field is not.
9) MillReportsRepository should be disposable.
10) Security (but low priority).
Data\DAL\ADO\MillReportsRepository.cs assigns queries directly using CommandText property. 
Consider using stored procedures. If any of such query will be obtained from user input in future, it will lead to SQL injection prossibility.
11) Quite strange to me:

<pre>
using (var connection = new SqlConnection(connectionString))
                
{
                    
   connection.Open();
                    
   connection.Close();
                
}
</pre>

In such codes, the connection will be disposed automatically after leaving using block, so connection.close() is redundant. Consider remove connection.close() from such blocks.

12) Not all repositories/view models disposes the disposable fields. 
E.g. in PrizmMainProject\Forms\Joint\ConstructionRepository.cs class Dispose() method should invoke Dispose() for each disposable object, not just for session.

**Comment by olga-jane** [comment]
3) leave helper. replace lambda by static method.

**Comment by olga-jane** [comment]
Prism-34
