### ISSUE TITLE
apply LocalizedItem for controls for following forms

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1040]
If there are some controls uncovered by LocalizedItem constructor, come to discuss it.

* [x] MillReportsXtraForm
* [x] SettingsXtraForm
* [x] SpoolsXtraForm
* [x] AboutXtraForm
* [x] PurchaseOrderXtraForm
* [x] PasswordChangeDialog
* [ ] MissingPortionsDialog
* [x] InspectionReportsXtraForm

changes could be put in several pull requests (all referencing this issue)

**Comment by demmy** [comment]
i not see MissingPortionsDialog as form MissingPortionsDialog not opening as Form on VS Designer #1101
