### ISSUE TITLE
apply LocalizedItem for controls for following forms (kpro)

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1042]
If there are some controls uncovered by LocalizedItem constructor, come to discuss it.

- [x] PartSearchXtraForm
- [x] AuditXtraForm
- [x] PartInspectionXtraForm
- [x] ExportForm
- [x] SaveDialog
- [x] ExternalFilesXtraForm
- [x] CreationDialog (please rename to more understandable name)
- [x] NumbersDialog (please rename to more understandable name)
- [x] ConflictDialog
- [x] ImportForm

InspectionAddEditXtraForm was changed on demmy's MillInspectionXtraForm

changes could be put in several pull requests (all referencing this issue)

**Comment by kapcia** [comment]
TODO:
Part search: select all
Audit: radiogroup
Export: tabs

**Comment by kapcia** [comment]
TODO:
Part search: select all 
PartInspectionXtraForm: results   repository combobox
MillInspectionXtraForm - everything
