### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1057]
Find out how to use log4net.
Discuss before coding, which messages at which levels should be present in our code.

**Comment by olga-jane** [comment]
4.5 isn't supported: http://logging.apache.org/log4net/release/framework-support.html

**Comment by olga-jane** [comment]
@DmitrySidorov please add logging Error-level on all throw's in program (see examples in Program.cs, LanguageManager.cs)

**Comment by DmitrySidorov** [comment]
part II:
- [ ] Warnings
- [ ] Info

**Comment by olga-jane** [comment]
Please make additional changes: 
set root value to ERROR (as it should go to Client)
    <root>
      <level value="DEBUG"/>
      <appender-ref ref="LogFileAppender"/>
    </root>
