### ISSUE TITLE
An unhandled NullReferenceException arrives at "Настройки->Инспекторы".

### ISSUE THREAD

**Issue by IgorVskpsn** [olga-jane/prizm#1072]
Steps to get the error message:
1. Go to "Настройки" tab and then to "Инспекторы" tab within it.
2. In the left part of the tab ("Типы сертификатов") create an empty-string item in the list. In order to do this you can start typing a new item's name and then remove all the symbols with backspace and change focus or just rename one of the existing items to an empty string.
3. Mark that item as active.
4. Now on the "Сертификаты" table within the "Инспекторы" frame try to select "Вид контроля" value. You should be able to see all the empty strings from the "Список типов" list in this combobox.
5. Select one of those empty strings.

Expected result: Getting the error message "Unhandled exception has occurred ... System.NullReferenceException: Object reference not set to an instance of an object. ..."

Note: You can create an empty-string items in any list like this. This probably could create other problems.

by: Igor Vysokopoyasniy

**Comment by olga-jane** [comment]
@AleksMorozova please, test on fresh installation on our testing computer

**Comment by olga-jane** [comment]
Still can save with empty strings
