### ISSUE TITLE
Saving records without the "Инспектор" field in the "Входной контроль" form.

### ISSUE THREAD

**Issue by IgorVskpsn** [olga-jane/prizm#1081]
Steps to reconstruct situation:
1. Start the program.
2. Go to "Входной контроль и строительство" -> "Контроль элементов трубопровода".
3. Press "Найти и редактировать для контроля" and choose any pipe or component.
4. Add a new record with any values to the table below, but don't set the "Инспектор" field.
5. Press "Сохранить" button.

Expected result: Record is successfully saved.

Could it be a logic mistake that a product's state can be changed without any inspector involvement?

by: Igor Vysokopoyasniy

**Comment by olga-jane** [comment]
@DmitrySidorov  please, test on fresh installation on our testing computer

**Comment by DmitrySidorov** [comment]
The version 1.0.30.0 (from 02.02.2014) has been sucssesfuly tested on our testing computer
