### ISSUE TITLE
"Поиск труб" specified dates do not affect search results

### ISSUE THREAD

**Issue by KhabarlakKonstantin** [olga-jane/prizm#1089]
Steps to reproduce:
1. Go to "Завод" -> "Поиск труб"
2. Set any date into "Дата сварки", "Дата наруждного покрытия", "Дата внутреннего покрытия"
3. Hit search
Expected result: only pipes with specified dates are shown
Actual result: specified dates do not affect search results

**Comment by olga-jane** [comment]
@KhabarlakKonstantin
