### ISSUE TITLE
"Измерение длины" OverflowException & Format Exception

### ISSUE THREAD

**Issue by KhabarlakKonstantin** [olga-jane/prizm#1091]
1. Go to "Завод" -> "Поиск труб"
2. Open any pipe -> "Контрольные операции"
3. Open "Длина трубы"
4. Set big number like 33333333333333333333333 in "Фактический"

Expected result: Error message
Actual result: System.OverflowException: Значение было недопустимо малым или недопустимо большим для Int32.

5. Or set number like 54,2
Actual result: System.FormatException: Входная строка имела неверный формат.

**Comment by AleksMorozova** [comment]
edit mask for factLimit at InspectionAddEditXtraForm. Mask should be "d10".
