### ISSUE TITLE
In "Новый стык" button "Сохранить" is never active

### ISSUE THREAD

**Issue by KhabarlakKonstantin** [olga-jane/prizm#1098]
1. Go to "Входной контроль и строительство" - "Новый стык"
2. Enter all fields

Actual result: Save button is never active.
But you can still save this "Стык" if you close tab and press "Сохранить изменения" - "Да"

![76](https://cloud.githubusercontent.com/assets/1634163/5936842/38af63fe-a6f1-11e4-8e10-14a5b879bd14.png)

**Comment by olga-jane** [comment]
accepted with note: later it should be changed, to use existing databinding

**Comment by DmitrySidorov** [comment]
The solution could be done in several ways:
- http://www.codewrecks.com/blog/index.php/2010/01/14/force-databinding-update-in-winform-without-waiting-for-lose-focus/
- http://stackoverflow.com/questions/2044435/c-sharp-databound-winform-control-does-not-retain-value-unless-you-leave-the-fie
