### ISSUE TITLE
"Параметры листа" -> "Номер" is wiped

### ISSUE THREAD

**Issue by KhabarlakKonstantin** [olga-jane/prizm#1110]
Steps to reproduce:
1. Create a new pipe
2. Go to "Поиск труб" find it and open
3. In "Контрольные операции" -- "Длина трубы"
Change "Результат" -- "Фактический" to 66
Change "Статус" to Passed
4. Press save
Actual result: values are saved, but "Общие параметры труб" -- "Параметры листа" -- "Номер" is now empty

**Comment by olga-jane** [comment]
@KhabarlakKonstantin

**Comment by KhabarlakKonstantin** [comment]
Already fixed in the latest master
https://github.com/olga-jane/prizm/commit/94beb38f3ed44c1592f8862435ddd1ac417f30b8
