### ISSUE TITLE
In "разрешение на отгрузку" pipes disappear

### ISSUE THREAD

**Issue by KhabarlakKonstantin** [olga-jane/prizm#1114]
Steps to reproduce:
1. Go to "Завод" -- "Разрешение на отгрузку"
2. Add a pipe
3. Click (or enter anything) into "Номер вагона" field
4. Click in any other field
Actual result: all pipes from "Список труб" disappear

**Comment by olga-jane** [comment]
нужна доработка: открытие разрешения
