### ISSUE TITLE
wrong validation for plate number for opening existing pipe

### ISSUE THREAD

**Issue by AleksMorozova** [olga-jane/prizm#1162]
Step:
1) Open existing pipe from search form
2) Update same of control operation and save this update
3) Save pipe

Expected result:
buttons save and save/new are enable

Actual result:
buttons save and save/new are disable

Reason:
Plate number is empty

**Comment by olga-jane** [comment]
@AleksMorozova  what does it mean "Update same of control operation and save this update"?

**Comment by DmitrySidorov** [comment]
have been fixed with
"add IsEditorActive check before refresh property value #1275"
