### ISSUE TITLE
Not all field names are localized

### ISSUE THREAD

**Issue by kapcia** [olga-jane/prizm#1163]
- [x] first setup form: Workstation type seems to be enum name
- [x] "no resource" at "saving settings" status message
- [x] Pipeline/operation type in grid seems to be enum name
- [x] Pipe status at mill seems to be enum name
- [x] mill pipe, inspection operations, False instead of No etc.
- [x] mill pipe, inspection operations, operation status seems to be enum name.
- [x] "no resource" release note status at search
- [x] Mill reports: inspection operations results seems to be enum names
- [x] "no resource" message+header at attempt editing empty pipe in spool
- [x] see type of entity at incoming inspection, window of choosing element
- [x] incoming inspection, element type seems to be enum name
- [x] save incoming inspection results, "no resource" in status bar
- [x] "no resource" at error saving spool
- [x] pipeline elements search: type in checked combo is taken from Enum
- [x] pipeline elements search: type in grid is taken from Enum
- [x] joint status at new joint is taken from Enum
- [x] status in grid at search joints seems to be taken from enum
- [x] type of report and type of Item in tracing report
- [x] label in tracing report (hardcoded)

new:
- [x] factBool at inspection edit form seems to work wrong in localized way
- [x] "no resource" at settings validation message (create new sizetype and do not enter it's parameter and try to save)

**Comment by olga-jane** [comment]
@kapcia  please come to discuss these translation issues, which of them it is possible to fix by standard ways

**Comment by kapcia** [comment]
Mill reports: inspection operations results seems to be enum names 
There is no LocalizedItem constructor for CheckedListBox control
