### ISSUE TITLE
Loading (Shipping) report at Mill

### ISSUE THREAD

**Issue by AleksMorozova** [olga-jane/prizm#1165]
Loading report doesn't display railcar information
Reason:
SubReportForLoadingXtraReport have wrong sqlDataSource (CustomSqlQuery should have right SQL query)
SQL query should be like this, but Xtra report doesn't processes such query:
select rn.number, r.number number,destination, certificate, n.length length,n.weight weight from Railcar r inner join (select SUM (length) length, sum (weight) weight, railcarId from Pipe group by railcarId) n on n.railcarId = r.id inner join releaseNote rn on rn.id=r.releaseNoteId

**Comment by kapcia** [comment]
Also removed from MillReports Repository unused method and query
