### ISSUE TITLE
final localization (omor)

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1168]

**Comment by olga-jane** [comment]
please add to description the list of views which were localized in this update

**Comment by AleksMorozova** [comment]
* [x] MillReportsXtraForm
* [x] SettingsXtraForm
* [x] SpoolsXtraForm
* [x] AboutXtraForm
* [x] PurchaseOrderXtraForm
* [x] PasswordChangeDialog
* [х] MissingPortionsDialog
* [x] InspectionReportsXtraForm
