### ISSUE TITLE
Impossible to send release note with "empty" railcars

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1186]
This feature is artefact of "railcar" implementation. It should be impossible to send release note when no pipes are in *release note* itself.

this code:

            foreach (Prizm.Domain.Entity.Mill.Railcar r in viewModel.Railcars) 
            {
                if (r.Pipes.Count == 0) 
                {
                    noPipe = true;
                }
            }

            if (noPipe)
            {
                notify.ShowError(Program.LanguageManager.GetString(StringResources.ReleaseNoteNewEdit_PipesAbsent), 
                    Program.LanguageManager.GetString(StringResources.Message_ErrorHeader));
                return;
            }

and commented code:

        public bool CanExecute()
        {
            return (!viewModel.Shipped
                && !string.IsNullOrWhiteSpace(viewModel.Number)); //&& viewModel.Pipes.Count != 0
        }

**Comment by demmy** [comment]
need save before ship
