### ISSUE TITLE
In "Роли" no rights are initially selected

### ISSUE THREAD

**Issue by KhabarlakKonstantin** [olga-jane/prizm#1210]
Go to Settings -> "Роли"
Actual result: It looks like Administator has no rights, but if you click on any other role and then back, rights are updated
![86](https://cloud.githubusercontent.com/assets/1634163/6006274/d89ebd98-ab19-11e4-9a33-4293e122b05a.png)

**Comment by olga-jane** [comment]
@KhabarlakKonstantin

**Comment by DmitrySidorov** [comment]
Continued be actual after testing: "Testing for 1.0.30.1 build (dsyd) #1235"
