### ISSUE TITLE
устанавливается флаг (*) изменений в настройках

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1250]
6.	Если просто открыть Настройки-Труба устанавливается флаг (*) изменений и при закрытии вкладки запрашивается подтверждение записи

**Comment by kapcia** [comment]
Issue is caused by rising pipesSizeListGridView_FocusedRowChanged event on SettingsXtraForm. When that event is risen,  viewModel.UpdatePipeTests(sizeType) is called and list of pipeTest is updated => form is modified

**Comment by kapcia** [comment]
Issue was fixed in pull request validation at Settings #996 #1347 and now is not reproduced
