### ISSUE TITLE
4.	В контрольных операциях Diapason заменить на Range

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1252]
4.	В контрольных операциях Diapason заменить на Range

make changes in English Translation and make sure russian version shows russian.
client said "Diapason" because enum value (string Diapason) is shown currently.

**Comment by kapcia** [comment]
Done in issue  Not all field names are localized #1163
Commited in pull-request: Localization: pipe test result status, inspections fact bool hardcoded, settings error message, control types and test results #1232

**Comment by olga-jane** [comment]
Done by creating correct translations
