### ISSUE TITLE
Translate en-EN into resource by ResGen, during packing installation package

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1256]
Translate en-EN into resource by ResGen, during packing installation package

And pack resource and place it in proper place.

**Comment by demmy** [comment]
RESULT = Strings.en-EN.resources
Strings.en-EN.txt(1826,1): warning RG0000: Duplicate resource key!  Name was: "ReleaseNoteNewEdit_Shipped"
Strings.en-EN.txt(2033,1): warning RG0000: Duplicate resource key!  Name was: "ControlTypeWitness"
Strings.en-EN.txt(2036,1): warning RG0000: Duplicate resource key!  Name was: "ControlTypeReview"
Strings.en-EN.txt(2039,1): warning RG0000: Duplicate resource key!  Name was: "ControlTypeMonitor"
Strings.en-EN.txt(2042,1): warning RG0000: Duplicate resource key!  Name was: "ControlTypeHold"
Strings.en-EN.txt(2045,1): warning RG0000: Duplicate resource key!  Name was: "Settings_CheckValues"
Strings.en-EN.txt(2048,1): warning RG0000: Duplicate resource key!  Name was: "Settings_ErrorHeader"
Strings.en-EN.txt(2051,1): warning RG0000: Duplicate resource key!  Name was: "TestResultTypeBoolean"
Strings.en-EN.txt(2054,1): warning RG0000: Duplicate resource key!  Name was: "TestResultTypeRange"
Strings.en-EN.txt(2057,1): warning RG0000: Duplicate resource key!  Name was: "TestResultTypeString"
Strings.en-EN.txt(2060,0): warning RG0000: Duplicate resource key!  Name was: "ConstractionReport_ReportTypeTracingReport"
Read in 676 resources from "Strings.en-EN.txt"
Writing resource file...  Done.
11 warnings(s).

**Comment by demmy** [comment]
File .\Languages\Resources\Strings.en-EN.resources no work
work .\Languages\Strings.en-**US**.resources w/o Resources folder

**Comment by demmy** [comment]
### missing translation
#### Main menu
all
#### New Pipe
номер листа
производитель
#### Waiting form
#### Release note
Добавление труб к текущему вагону
Номер трубы
Список труб
#### Settings
#####    Pipe
      параметры типоразмера
#####    PipeLine
      набор операций ...
#####    Inspectors
      Инспекторы
         column - уровень
         column - активен
#### Notification
