### ISSUE TITLE
Saving empty row at Settings

### ISSUE THREAD

**Issue by AleksMorozova** [olga-jane/prizm#1278]
It's possible to save all settings with empty data

this is additional fix after "An unhandled NullReferenceException arrives at "Настройки->Инспекторы". #1072"

**Comment by olga-jane** [comment]
could you review code and discuss possible solutions (write propositions here in comments)

**Comment by AleksMorozova** [comment]
My preposition is InvalidRowException event where we could set  ExceptionMode to NoAction and users wouldn't have opportunity to save or to leave page while he has some empty data. Welders grid has this event.

**Comment by olga-jane** [comment]
please rename 
Settings_ValueRequaered
to 
Settings_ValueRequired
everywhere:
  D:\00_PROJECTS\PRIZM\prizm\src\bin\Debug\Languages\Strings.en-EN.txt(363):Settings_ValueRequaered=Value is required
D:\00_PROJECTS\PRIZM\prizm\src\bin\Debug\Languages\Strings.template.txt(528):Settings_ValueRequaered=
  D:\00_PROJECTS\PRIZM\prizm\src\bin\Release\Languages\Strings.en-US.txt(374):Settings_ValueRequaered=Value is required
  D:\00_PROJECTS\PRIZM\prizm\src\PrizmMainProject\Languages\StringResources.cs(1023):            Id = "Settings_ValueRequaered",

and in Resources.resx
