### ISSUE TITLE
Pipe doesn't have railcar reference  

### ISSUE THREAD

**Issue by kapcia** [olga-jane/prizm#1330]
Please, see attached screenshots
![1](https://cloud.githubusercontent.com/assets/7581458/6145417/46619630-b1ea-11e4-8072-7f0ea000d9a7.png)
![2](https://cloud.githubusercontent.com/assets/7581458/6145418/4ad8e33a-b1ea-11e4-888a-e6c6c9e1f095.png)

**Comment by olga-jane** [comment]
fixed under Release note problems (client 6 Feb 2015) #1265
