### ISSUE TITLE
Release note: impossible to ship railcar (missing pipes)

### ISSUE THREAD

**Issue by kapcia** [olga-jane/prizm#1355]
STR:
Open Mill-> Release note
Fill in required fields
Add pipes
Click Ship
Expected result: railcar is shipped
Actual result: Message about missing pipes is shown
Please,see attached screenshot
![1](https://cloud.githubusercontent.com/assets/7581458/6184390/cc368628-b369-11e4-97a6-8a8d7ff8f3b7.png)

**Comment by olga-jane** [comment]
fixed here 
Crash on release note (not saved - transient instance) #1354
