### ISSUE TITLE
Can't do anything while Text Box is empty

### ISSUE THREAD

**Issue by Jeanosis** [olga-jane/prizm#1399]
When this bug appears you can't even close the program.

Instruction:
1.Open "Mill" menu(Create new pipe).
2.Select "New Pipe(Ctrl+P)".
3.Click on "Pipe Number" Text Box.
4.Loose focus to that Text Box(click somewhere else etc.)
![image](https://cloud.githubusercontent.com/assets/11027096/6211217/80d2a846-b5e0-11e4-9b1a-3d445eed3ad1.png)

Yefremov Stanislav

**Comment by AleksMorozova** [comment]
not reproduced, seems to be fixed at Crash at exit when Modified is on #1352
