### ISSUE TITLE
Problem with translation from English: Mill-Pipe, expected result and yes/no deactivation

### ISSUE THREAD

**Issue by TanyaPilipenko** [olga-jane/prizm#1401]
Mill->New pipe->Inspected operations.
In column "Expected result" there are except point "Нет" point "False".

Mill->New pipe->Inspected operations.
If I click "Deactivate pipe" as a result in window buttons "Yes" and "No" in the English.

**Comment by olga-jane** [comment]
Testing failed. Moved to next build.
Testing comment: "2) Problem with translation from English: Mill-Pipe, expected result and yes/no deactivation"
