### ISSUE TITLE
Истечение срока годности пароля

### ISSUE THREAD

**Issue by Chifuyu** [olga-jane/prizm#1406]
Дата истечения пароля у пользователя стоит на определенное число после изменения системной даты на большее число, то при попытке зайти в программу должно выскакивать окошко о смене пароля, но оно не выскакивает.

Создайте пользователя в программе
Установите ему дату истечение пароля на какое то число
Сохраните
Выйдете из программы
Измените системную дату на число превышающее число в пункте 2
Запустите программу
Попробуйте войти под именем этого пользователя
Заходит, но должно вылетать окошко для смены пароля

Хоменко

**Comment by olga-jane** [comment]
please write your propositions about fix

**Comment by kapcia** [comment]
Issue is caused by out of date data about logged user. I would prefer while saving users update data about current user. Please, see solution in branch Protsenko_v1
