### ISSUE TITLE
Close button does not work with an empty input field

### ISSUE THREAD

**Issue by YuriyZagorulko** [olga-jane/prizm#1409]
Settings/pipe , then click on the  empty input field.
![image](https://cloud.githubusercontent.com/assets/11027764/6212160/a813d4b6-b5ea-11e4-98cb-ba4a69549c0e.png)
Then, without clicking on anything else, choose file/exit/save (or don't save) and you'll get an error .
![image](https://cloud.githubusercontent.com/assets/11027764/6212199/0990e7e2-b5eb-11e4-8f81-0350b62b0ba5.png)
![image](https://cloud.githubusercontent.com/assets/11027764/6212273/cbac686a-b5eb-11e4-828c-2270c71d2be2.png)

**Comment by olga-jane** [comment]
seems to be same as 
Crash at exit when Modified is on #1352
