### ISSUE TITLE
Translate problems in different places

### ISSUE THREAD

**Issue by Chifuyu** [olga-jane/prizm#1421]
Incomining inspection and constructions - Find joins - Search results - статус
![incomining inspection and constructions - find joins - search results -](https://cloud.githubusercontent.com/assets/10714201/6224910/5f999dea-b68c-11e4-847c-0b6088a70693.png)

Incomining inspection and constructions - Spools - Входной контроль
![incomining inspection and constructions - spools -](https://cloud.githubusercontent.com/assets/10714201/6224919/7c9dac60-b68c-11e4-989e-0ec4b8de8812.png)

Incomining inspection and constructions - Tracing reports - Report type - By used products - Type - Выбрать все
maybe report mustb in english to
![incomining inspection and constructions - tracing reports - report type - by used products - type -](https://cloud.githubusercontent.com/assets/10714201/6224921/84980ab4-b68c-11e4-8973-737fc7df3338.png)

Mill - New release note - attachments
![mill - new release note - attachments](https://cloud.githubusercontent.com/assets/10714201/6224923/8d0751fa-b68c-11e4-9e43-835a36285bd6.png)

Mill - New release note
![mill - new release note](https://cloud.githubusercontent.com/assets/10714201/6224926/950604dc-b68c-11e4-9cdc-95adb3ea0c45.png)

Miskellaneous - Notifications - все окно на русском
![miskellaneous-notifications -](https://cloud.githubusercontent.com/assets/10714201/6224928/a31cf5da-b68c-11e4-8d6e-7c10d73fedfd.png)

settings -  pipe -  list of inspetrion operstions for selected pipe size -  код
and i think that size type parameters - seam type must be in english
![settings pipe list of inspetrion operstions for selected pipe size](https://cloud.githubusercontent.com/assets/10714201/6224930/aadec596-b68c-11e4-886c-80ae53250f47.png)

settings -  project  - технические параметры на русском языке
![settings project](https://cloud.githubusercontent.com/assets/10714201/6224932/b3dab394-b68c-11e4-919a-8f223e3d2183.png)

settings - users - роли
![settings - users -](https://cloud.githubusercontent.com/assets/10714201/6224938/bc4fdbc6-b68c-11e4-802e-8de6052c30d5.png)

Хоменко

**Comment by gasty** [comment]
![5](https://cloud.githubusercontent.com/assets/11043173/6264923/0800f99c-b831-11e4-9e44-6cb20a954a51.png)
