### ISSUE TITLE
Language settings - check goes wrong

### ISSUE THREAD

**Issue by Chifuyu** [olga-jane/prizm#1423]
If i last time had an english language in program, when i run program again i have all in engkish but in settings language selected russian

run program 
settings - language - change language into english
exit
run program
settings - language. selected russian but program on english so select must be english
![language](https://cloud.githubusercontent.com/assets/10714201/6225137/de69fa82-b68e-11e4-8f9c-ba76a74b4e79.png)
Хоменко

**Comment by kapcia** [comment]
Will be fixed after #1389 is merged

**Comment by olga-jane** [comment]
fixed under Save language settings as user settings #1032
