### ISSUE TITLE
Re-saving window at heat and purchase order

### ISSUE THREAD

**Issue by Stasplahtii** [olga-jane/prizm#1426]
Завод ->новая труба-> field  "Плавка"
Trying to create a new heat 
Put a cursor in the heat field 
![1](https://cloud.githubusercontent.com/assets/11027688/6225196/b51f4f46-b68f-11e4-9f06-f47887db651a.JPG)
Type a new heat 
![2](https://cloud.githubusercontent.com/assets/11027688/6225214/edbfb6f6-b68f-11e4-8373-404d6b1778ab.JPG)
click three dots in order to save a new heat and press "save" 
![3](https://cloud.githubusercontent.com/assets/11027688/6225242/462e7016-b690-11e4-818f-77b983759114.JPG)
click "save" in a new window
try to put other parameters of the new pipe
We can see a save window again 
![4](https://cloud.githubusercontent.com/assets/11027688/6225292/c6c212a0-b690-11e4-9b73-8ad410595b8e.JPG)
press save and save again 
THE SAME BUG WITH PURCHASE ORDER FIELD

**Comment by olga-jane** [comment]
PRISM-29
