### ISSUE TITLE
New Pipe - New Heat translation bug Да/Нет

### ISSUE THREAD

**Issue by Kosenko-Yuriy** [olga-jane/prizm#1433]
In Mill project:
Mill -> New Pipe
I can write new Heat number and press enter, then I see this form (in english version):
![2](https://cloud.githubusercontent.com/assets/11027664/6226177/3b244eec-b69b-11e4-8fbc-27c12550cc79.jpg)
after presse "Да" 
![3](https://cloud.githubusercontent.com/assets/11027664/6226195/63b52980-b69b-11e4-92d6-f8419e06c317.jpg)
Now I press "save" in this and next forms without filling required field "plate manufacturer"
![4](https://cloud.githubusercontent.com/assets/11027664/6226220/99a70054-b69b-11e4-90e2-3b601f31a643.jpg)
correct error simbol
![1](https://cloud.githubusercontent.com/assets/11027664/6226232/b874eec4-b69b-11e4-805a-093656aa76e1.jpg)
But I can choice this "00000005" in drop-down list and then select other fielt -> error simbol missing and I can save errored pipe
![1](https://cloud.githubusercontent.com/assets/11027664/6226281/37cefc5a-b69c-11e4-8ed5-1a81d4f64e8a.jpg)

**Comment by demmy** [comment]
Create new heat it's a separate scenario in separate form after which heat field be cleared & new heat put to dropbox

**Comment by olga-jane** [comment]
functionality problem is duplicated to "Re-saving window at heat and purchase order #1426".

This issue will concern translation problem only.

**Comment by olga-jane** [comment]
Standard message boxes with questions: either special windows language packs should be used or (seems to be more universal in our case) special dialogs should be created instead of standard message boxes (think about their simplicity and universality, i.e. pictures for error and so on. discussion required).

**Comment by olga-jane** [comment]
PRISM-27
