### ISSUE TITLE
Problem with adding pipes to current railcar

### ISSUE THREAD

**Issue by TanyaPilipenko** [olga-jane/prizm#1435]
Завод -> Разрешение на отгрузку.
Пункт: Добавление труб к текущему вагону.

I can't choise and add pipe.

**Comment by demmy** [comment]
What is meant 
> current railcar
cant reproduce

**Comment by olga-jane** [comment]
@TanyaPilipenko, please provide more detailed scenario

**Comment by TanyaPilipenko** [comment]
Sorry, it isn't bug.
Просто я не разобралась, что нельзя добавлять трубу для отгрузки, пока у неё не будет статус "на складе".
