### ISSUE TITLE
Problem with exit from program without saving [Exception]

### ISSUE THREAD

**Issue by VladBekleneshev** [olga-jane/prizm#1436]
1) Launch Mill or Construction
2) Just enter anything in any field
3) Do not close the current tab
4) File->Exit-> Do not save-> and get this 
![exception](https://cloud.githubusercontent.com/assets/11027650/6226627/b812d5f0-b69f-11e4-9521-b64a80bd1f46.JPG)

**Comment by kapcia** [comment]
Duplicate of #1409
Seems to be the same as
Crash at exit when Modified is on #1352

**Comment by olga-jane** [comment]
confirmed duplicated
