### ISSUE TITLE
You can't select anything else, if you'll click on field with new user

### ISSUE THREAD

**Issue by YuriyZagorulko** [olga-jane/prizm#1439]
Settings->Users click on the bottom field , enter something , then delete it
![image](https://cloud.githubusercontent.com/assets/11027764/6227014/57c4c560-b6a3-11e4-9fdf-aaf977448f66.png)
then you can not select anything else until you fill in all fields.

**Comment by olga-jane** [comment]
@AleksMorozova @demmy how it looks according to our latest concept of settings validation?

**Comment by demmy** [comment]
IMHO normally - same as welders & certificates
user has lockout on row only add new row & add some incorrect (not full) data
If user not want to save it ESC delete newery added row

**Comment by AleksMorozova** [comment]
I agree with demmy. If user enter correct and full data he doesn't lock on row, otherwise he should be immediately inform about incorrect data and correct it. Inform about all wrong data at saving not so comfortable for user because of a sufficiently large number of individual pages.
