### ISSUE TITLE
You can't open the program if users have the same logins

### ISSUE THREAD

**Issue by YuriyZagorulko** [olga-jane/prizm#1440]
Settings->Users add two users with the same logins
![image](https://cloud.githubusercontent.com/assets/11027764/6227084/e02efd30-b6a3-11e4-8adc-12c51cd7aef9.png)
then you can't use this login when you open the program, but you can enter other logins
![image](https://cloud.githubusercontent.com/assets/11027764/6227114/261430ae-b6a4-11e4-956a-f29acbd71b69.png)
![image](https://cloud.githubusercontent.com/assets/11027764/6227118/38125c68-b6a4-11e4-9b69-a40328b2c8c3.png)

**Comment by AleksMorozova** [comment]
fixed at duplicate login #1412
