### ISSUE TITLE
We cannot change admin password

### ISSUE THREAD

**Issue by KnightDanila** [olga-jane/prizm#1446]
We cannot change admin password (also we cannot change other information)
![image](https://cloud.githubusercontent.com/assets/11027679/6228039/5973c894-b6c0-11e4-8be9-01dc69a0ab8d.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6228040/5eb7f3d4-b6c0-11e4-987b-8361839107de.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6228043/62e85db8-b6c0-11e4-906f-f8d01913e3c3.png)
But, old password is still working
Egoshkin Danila

**Comment by kapcia** [comment]
Related issue: Истечение срока годности пароля #1406
