### ISSUE TITLE
Empty password for user is possible

### ISSUE THREAD

**Issue by gasty** [olga-jane/prizm#1449]
Для пользователей, не администраторов, разрешается пустой пароль (с помощью настройки->Пользователи)

Настя Горбань

**Comment by olga-jane** [comment]
find out how to deal with password (at the level of adm and at the level of change password on login)

**Comment by gasty** [comment]
More detailed description of bag:
1. Open Settings->Users.
2. Add to table new user: input his login, surname, name/
3. Click to Password.
4. In the open window nothing input and click ok. 
5. Save and exit.

Programm allowed me not to create password for new user, in fact.
Check authorization of this user:
1. Run program.
2. In start window input login, password field is empty.
3. Click "Log In".
Result: program opened without errors.
This is realy in case if check roles of administrator and not administrator for new user.
BUT: if try to change password of user wich was created during install of program, program report an error, so in this case program didn't save changes with empty password, but didn't report about one.

 so, may be, problem is could be fixed if to add additional check in window Settings->Users->Password.

Why not change password of creator of database?This bag related with bag of Danila, I think.He found problem with changing password of creator database. This password does not change at all. So this could be related with some special status and permissions of creator. But can add, that if change password of this login from other user with role of administrator changes will be save.

**Comment by gasty** [comment]
After a few additional checks I can add, that change the password is not saved only current user-administrator. So this part of bag is could be related with some problems in code of SQL-query. May be, somewhere there is a request (Log in autorization, for example) which doesn't stop to apply of this record. this is my guess, but it's hard to suggest anything without knowing the code.

**Comment by kapcia** [comment]
This issue is related to #1406 : while saving settings data about current logged user is not refreshed.
