### ISSUE TITLE
Translate problem on standard message box

### ISSUE THREAD

**Issue by Paradaimu** [olga-jane/prizm#1453]
1) Create new release note (don't close)
2) Release note search 
3) Choose realise you just created

http://clip2net.com/clip/m0/a3e92-clip-69kb.png?nocache=1
![image](https://cloud.githubusercontent.com/assets/8179067/6230175/3f0a01ca-b6c6-11e4-8f47-081f01ae04a7.png)

Komkov Sviatoslav

**Comment by olga-jane** [comment]
related to "New Pipe - New Heat translation bug Да/Нет #1433" and will be fixed there (if will)

**Comment by olga-jane** [comment]
PRISM-27
