### ISSUE TITLE
Choose role in empty user tab cause unhandled exception

### ISSUE THREAD

**Issue by Paradaimu** [olga-jane/prizm#1454]
1) Users
2) New user form(empty)
3) Close settings, try to save and:

![image](https://cloud.githubusercontent.com/assets/10973525/6230799/1e81f9ee-b6cb-11e4-8f4e-929dfd8d8ccc.png)

Komkov Svyatoslav

**Comment by olga-jane** [comment]
@AleksMorozova pls check duplication

**Comment by AleksMorozova** [comment]
this task isn't duplicate and needed to be fixed the same way as inspector and certificates
