### ISSUE TITLE
Some russian words in the english localisation

### ISSUE THREAD

**Issue by Paradaimu** [olga-jane/prizm#1456]
![image](https://cloud.githubusercontent.com/assets/10973525/6231212/f5a4f910-b6cd-11e4-9f72-b5863e8937a5.png)

http://clip2net.com/s/3cDAQeC
![image](https://cloud.githubusercontent.com/assets/10973525/6231245/29b7144a-b6ce-11e4-91e5-7a7991cc30ca.png)

![image](https://cloud.githubusercontent.com/assets/10973525/6231274/5c9f01f6-b6ce-11e4-95fd-992d29b4e434.png)

![image](https://cloud.githubusercontent.com/assets/10973525/6231314/9d27c8c0-b6ce-11e4-92fe-88972d3ef0f1.png)

Komkov Svyatoslav

**Comment by AleksMorozova** [comment]
already fixed
