### ISSUE TITLE
Negative number at Settings -> Welders -> Grade

### ISSUE THREAD

**Issue by vlad0994** [olga-jane/prizm#1459]
Settings -> Welders -> Grade
In numeric fields we can enter negative number. 
![image](https://cloud.githubusercontent.com/assets/11043155/6244199/9dfd9556-b758-11e4-8a15-acdb8762dc90.png)

Tkachenko Vlad

**Comment by olga-jane** [comment]
@AleksMorozova seems to be duplicated, please reference

**Comment by AleksMorozova** [comment]
same issue: No limiter on input field Grade #1464
