### ISSUE TITLE
Problem with translation from Russian.

### ISSUE THREAD

**Issue by TanyaPilipenko** [olga-jane/prizm#1461]
Settings->Project
Not translate these points.
![1](https://cloud.githubusercontent.com/assets/11027648/6244330/a63b0b2a-b75a-11e4-8556-41d50389768d.jpg)
+
![2](https://cloud.githubusercontent.com/assets/11027648/6244375/7a525c92-b75b-11e4-9d95-208da0f66d1d.jpg)

**Comment by AleksMorozova** [comment]
already fixed
