### ISSUE TITLE
Error when creating a new joint 

### ISSUE THREAD

**Issue by Stasplahtii** [olga-jane/prizm#1462]
Create a new pipeline and save
![image](https://cloud.githubusercontent.com/assets/11027688/6244226/fb9d9332-b758-11e4-8eed-4e0dc6d16337.png)
New joint 
![image](https://cloud.githubusercontent.com/assets/11027688/6244323/93c51198-b75a-11e4-95bd-2abc42eea166.png)
trying to add weld and repair 
chose already created inspection name 
![image](https://cloud.githubusercontent.com/assets/11027688/6244328/a2654286-b75a-11e4-80dc-a12ac4823dea.png)
and error 
![image](https://cloud.githubusercontent.com/assets/11027688/6244342/fbb95ba6-b75a-11e4-9686-b726c4cb1822.png)

**Comment by olga-jane** [comment]
low priority for 32
@DmitrySidorov also pay attention to the status of new joint, is it correct?
