### ISSUE TITLE
Не корректно отображается статус трубы – На складе/Отгружена

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1468]
Не корректно отображается статус трубы – На складе/Отгружена, трубы 1010 до 1051 в БД: они были внесены в список при формировании разрешения на отгрузку, но разрешение было закрыто, вероятно с сохранением, но без отгрузки. 
В результате, в таблице Поиск труб статус На складе, а при просмотре трубы на вкладке Общие параметры трубы Параметры отгрузки заполнены. (писал вчера вечером, возможно просто надо описать процесс формирования разрешений на отгрузку)

**Comment by olga-jane** [comment]
@DmitrySidorov please look

**Comment by DmitrySidorov** [comment]
Статус "Отгружена" труба приобретает посте отгрузки, если разрешение на отгрузку сохранено, но отгрузка не произошла у трубы остается статус "На складе". При этом труба имеет параметры разрешения на отгрузку в котором она была сохранена. Данное поведение предполагалось нормальным.
Возможно, необходим дополнительный стату "Сохранена для отгрузки"?

**Comment by olga-jane** [comment]
client has been asked

**Comment by olga-jane** [comment]
Solution is confirmed:
add new pipe status (Ready to ship/Готова к отгрузке)
if pipe is in railcar, it should have this status.
