### ISSUE TITLE
Empty database fields error

### ISSUE THREAD

**Issue by Jeanosis** [olga-jane/prizm#1473]
Similar with Issue #1432, but more problematic.

Problem with empty fields now occurs at "Welders" panel at "Settings". So you can save some data(a welder, an inspector etc.) with empty fields to database and that leads to regular exceptions & UI crashing(Pic. 3) while program working with it. And that can't be fixed cause you can't remove "wrong" records(program is broken until you delete all saves).

Instruction:
1. Open "Settings" menu
2. Select "Welders" panel
3. Click to Check Box(Pic. 1)
4. Try to close "Settings" panel(Pic. 2)
5. Select "Save"(Pic. 2)
6. Click to Check Box(Pic 1)
7. Try to close "Settings" panel(Pic. 2)
8. Select "Do not save"(Pic. 2)
9. Close "Settings"
10. Open "Settings" menu
11. Select any panel

Also, exception occurs when you open program after "empty fields" problem committed.

Pic. 1
![bug6_1](https://cloud.githubusercontent.com/assets/11027096/6245008/d83dfbac-b762-11e4-8bda-1db595d885b0.png)
Pic. 2
![bug6_2](https://cloud.githubusercontent.com/assets/11027096/6245014/e17ae81a-b762-11e4-9eb7-48cbfe034e94.png)
Pic. 3
![bug6_3](https://cloud.githubusercontent.com/assets/11027096/6245017/e43fe85c-b762-11e4-8f8f-e920fa562e47.png)

Yefremov Stanislav

**Comment by olga-jane** [comment]
@AleksMorozova is it duplicated? which our task fixes all empty fields and when fixed and is tested
