### ISSUE TITLE
Pipe size parameters cloning

### ISSUE THREAD

**Issue by Jeanosis** [olga-jane/prizm#1481]
After importing pipes with "1500 X 100500 X 50 - Прямой" size parameter it's cloning itself at "Pipes" panel at "Settings"(Pic.4).

Instruction:
1. Import *.prism file(Pic. 1)
2. Open "Settings" menu
3. Select "Pipes" panel(Pic. 2 - before, Pic. 3 - after)

Pic. 1
![bug7_1](https://cloud.githubusercontent.com/assets/11027096/6245614/30d6fefc-b769-11e4-9c65-e5df45c6d72c.png)
Pic. 2
![bug7_2](https://cloud.githubusercontent.com/assets/11027096/6245615/324b14d0-b769-11e4-873c-d670e3c64b05.png)
Pic. 3
![bug7_3](https://cloud.githubusercontent.com/assets/11027096/6245616/341e2ef0-b769-11e4-9cc3-3b746a6aa251.png)
Pic.4
![bug7_4](https://cloud.githubusercontent.com/assets/11027096/6245618/366ed0e2-b769-11e4-87a2-ac1b47a7c054.png)

Yefremov Stanislav

**Comment by Paradaimu** [comment]
Althought when you try to save this construction, the programm save it. If you put in 20-30 copies and try to save them, the programm will stuck and freeze.

**Comment by olga-jane** [comment]
to develop a solution
