### ISSUE TITLE
Инспекторы и сертификаты - выбрать Ещё не существующего инспектора

### ISSUE THREAD

**Issue by Kosenko-Yuriy** [olga-jane/prizm#1482]
В дополнение к #1432 
Если выбрать существующего инспектора с существующими сертификатами
![1](https://cloud.githubusercontent.com/assets/11027664/6245712/f103514e-b769-11e4-9a8c-3d96d17d0e80.jpg)
Потом выбрать Ещё не существующего инспектора
![2](https://cloud.githubusercontent.com/assets/11027664/6245721/11a89440-b76a-11e4-829a-0fe373d1959d.jpg)
То сертификаты предыдущего никуда не денутся, а при попытке добваить новый сертификат возникнет ошибка приводящая к падению программы (возникает при смене "фокуса" на другой пункт)
![3](https://cloud.githubusercontent.com/assets/11027664/6245789/cac1f138-b76a-11e4-9b46-719ac147cd25.jpg)

![4](https://cloud.githubusercontent.com/assets/11027664/6245769/a351998c-b76a-11e4-9c70-d4ffcab64f6c.jpg)

**Comment by AleksMorozova** [comment]
main task is: Error in "Inspectors" panel #1405

also this task is already fixed
