### ISSUE TITLE
unexpected error - "Сертификаты" then press 'Esc' or 'Alt'

### ISSUE THREAD

**Issue by YuriyZagorulko** [olga-jane/prizm#1484]
"Настройки"->"Инспекторы" , click on the window "Сертификаты" then press 'Esc' or 'Alt' 
![image](https://cloud.githubusercontent.com/assets/11027764/6246113/0f7cb792-b76e-11e4-90f6-ee4356dc9bf6.png)

**Comment by AleksMorozova** [comment]
main task is: Error in "Inspectors" panel #1405

also this task is already fixed
