### ISSUE TITLE
Strange Roles 0_o

### ISSUE THREAD

**Issue by KnightDanila** [olga-jane/prizm#1487]
Strange Roles 0_o
1. I did it
![image](https://cloud.githubusercontent.com/assets/11027679/6246544/b064ede0-b783-11e4-96fb-422fd371f2b0.png)
2. Then, I cleaned it
![image](https://cloud.githubusercontent.com/assets/11027679/6246550/bbaea4d4-b783-11e4-93a6-54e0e90ce8e0.png)
3. Now, press ESC, and it will be empty
![image](https://cloud.githubusercontent.com/assets/11027679/6246554/c3ed7e40-b783-11e4-9d00-10f7f471646a.png)
4. I cannot delete it!? But it is not all, if I went to Users, I will see this clean Roles, and I can use it
![image](https://cloud.githubusercontent.com/assets/11027679/6246561/cedebf4e-b783-11e4-9f79-30a251e43b01.png)
Egoshkin Danila

**Comment by olga-jane** [comment]
@AleksMorozova is it duplicated to empty records problem

**Comment by AleksMorozova** [comment]
main task: Choose role in empty user tab cause unhandled exception #1454
