### ISSUE TITLE
Click in empty nothification bar cause unhandled exeption

### ISSUE THREAD

**Issue by Paradaimu** [olga-jane/prizm#1492]
1) Choose notification (must be empty)
2) Click in empty field, or try to sort

![image](https://cloud.githubusercontent.com/assets/10973525/6247963/504ee992-b783-11e4-81c8-9d0b476b0b62.png)

Komkov Svyatoslav

**Comment by Jeanosis** [comment]
#1424

**Comment by AleksMorozova** [comment]
already fixed at this commits click at empty grid #1429
