### ISSUE TITLE
После импорта не видит вложенные файлы v 1.0.32.9991

### ISSUE THREAD

**Issue by Chifuyu** [olga-jane/prizm#1501]
Создать трубу
Добавить вложенные файлы во вкладке "вложения" 
Создать разрешение на отгрузку
Добавить файлы во вкладке "вложения" 
Сохранить 
Отгрузить 
Экспортировать 
Импортировать в другую программу (Мастер/Строительство)
Зайти на вкладку завод - поиск труб
Найти нашу трубу и открыть
Просматриваем вложенные файлы и там пусто
Зайти на вкладку "завод - Поиск разрешений на отгрузку"
Найти наше разрешение и открыть
Просматриваем вложеные файлы и там пусто

![5354](https://cloud.githubusercontent.com/assets/10714201/6263346/d5daadda-b81e-11e4-854b-037f7976247e.png)
![jsefkwneag](https://cloud.githubusercontent.com/assets/10714201/6263351/e019986a-b81e-11e4-8396-b4e254291b92.png)

Хоменко

**Comment by kapcia** [comment]
Cannot reproduce.
And as far as I see from screenshots, attachments windows are opened for different pipes

**Comment by Chifuyu** [comment]
Извиняюсь, проблема была в старой версии. В новой трубы перепутала

**Comment by Chifuyu** [comment]
Так же такая проблема есть и с катушками. При создании катушки прикрепляем файлы и после импорта их не видно

![default](https://cloud.githubusercontent.com/assets/10714201/6272899/e49d7712-b873-11e4-9a96-343b74c94f96.png)

![1](https://cloud.githubusercontent.com/assets/10714201/6272901/ea07b2da-b873-11e4-8f42-1a637e122074.png)
