### ISSUE TITLE
Argument out of range exception in Search Pipeline Elements [Master] [Exception] 1.0.32.9991

### ISSUE THREAD

**Issue by VladBekleneshev** [olga-jane/prizm#1510]
0) Open Master
1) Incoming Inspection and Construction->Find Elements
2) Try to enter "24" (for example) in Type in search results
3) We can see this exception:
![out_of_range](https://cloud.githubusercontent.com/assets/11027650/6264256/dcd8686e-b82a-11e4-90a6-ee5753acf89b.JPG)

**Comment by olga-jane** [comment]
restrict editing search result grid
