### ISSUE TITLE
Design v.1.0.32.9991

### ISSUE THREAD

**Issue by Stasplahtii** [olga-jane/prizm#1511]
I can change design by right clicking "Customize Layout"
![default](https://cloud.githubusercontent.com/assets/11027688/6264298/4b2abd94-b82b-11e4-9e2e-cb71c3fa3320.JPG)
There are some words in English and Russian Language in one window

**Comment by prag007** [comment]
Find design bug!
[DRAG AND DROP ELEMENTS]
1)Construction -> Incoming expection and construction.
![image](https://cloud.githubusercontent.com/assets/11043511/6264361/1e24fe08-b82c-11e4-9ff6-b4bf384aa491.png)
2) press LMB on inspection date (for example, working with almost all design elements) and drag it of it's place.
like that: 
![image](https://cloud.githubusercontent.com/assets/11043511/6264398/770f343e-b82c-11e4-80ff-5a1989df0fec.png)

**Comment by olga-jane** [comment]
not bugs
