### ISSUE TITLE
Open one pipe twice

### ISSUE THREAD

**Issue by Jeanosis** [olga-jane/prizm#1516]
There is a possibility of opening same pipe more then once(Pic. 3).

Instruction(1.0.32.9991 version):
1. Open "Mill" menu
2. Select "New Pipe" panel
3. Enter some data(Pic. 1)
4. Save pipe
5. Open "Mill" menu
6. Select "Find pipes" panel
7. Find recently created pipe(Pic. 2)
8. Change pipe's size type(for example, прямой -> бесшовный)
9. Select "Find pipes" panel
10. Open recently created pipe

Pic. 1
![bug8_1](https://cloud.githubusercontent.com/assets/11027096/6264432/a8f504ce-b82c-11e4-9c14-9f1deb0b73f7.png)
Pic. 2
![bug8_2](https://cloud.githubusercontent.com/assets/11027096/6264434/abcefc86-b82c-11e4-988a-b3cb9068faa1.png)
Pic. 3
![bug8_3](https://cloud.githubusercontent.com/assets/11027096/6264435/ae291854-b82c-11e4-87b2-1ca583730c9f.png)

Yefremov Stanislav

**Comment by olga-jane** [comment]
@KhabarlakKonstantin
