### ISSUE TITLE
can't save settings "settings"->pipe (version 1.0.32.9992)

### ISSUE THREAD

**Issue by YuriyZagorulko** [olga-jane/prizm#1533]
1.chose "settings"->pipe
2.click on "Copy size type" two times ,then you'll see red rows.
![image](https://cloud.githubusercontent.com/assets/11027764/6284157/d65b52e6-b8f5-11e4-97ea-e1ff462c6e96.png)
3.delete that red rows (click on them and press "delete")
![image](https://cloud.githubusercontent.com/assets/11027764/6284169/065a8ad4-b8f6-11e4-8043-196e8a05f552.png)
Then, when you delete them you still can't save settings.
![image](https://cloud.githubusercontent.com/assets/11027764/6284183/355e0e46-b8f6-11e4-83c3-0f680f5d444a.png)

**Comment by AleksMorozova** [comment]
already fixed - fix settings Validation #1565
