### ISSUE TITLE
Incorrect error of invalid value in Settings->Componentry v. 1.0.32.9992

### ISSUE THREAD

**Issue by gasty** [olga-jane/prizm#1536]
v. 1.0.32.9992

1. Settings
2. Componentry
3. Input "Component type" and "Number of connections"
4. Click "Save"
5. 

![8](https://cloud.githubusercontent.com/assets/11043173/6284603/7ed4fcf2-b8fa-11e4-8cdd-fbdd4f0008f8.png)

Gorban

**Comment by gasty** [comment]
![9](https://cloud.githubusercontent.com/assets/11043173/6284783/ea54bf74-b8fc-11e4-8f0b-8316567c25ea.png)
![10](https://cloud.githubusercontent.com/assets/11043173/6284784/ea5b4704-b8fc-11e4-8b11-8fe6ef379ae7.png)
![11](https://cloud.githubusercontent.com/assets/11043173/6284785/ea5c3b00-b8fc-11e4-8c99-360e8377d4c0.png)

**Comment by Chifuyu** [comment]
#1540
