### ISSUE TITLE
Error when saving a new pipe  v. 1.0.32.9992

### ISSUE THREAD

**Issue by vlad0994** [olga-jane/prizm#1538]
When complete all fields in the Mill -> Pipe and double-click on save
![image](https://cloud.githubusercontent.com/assets/11043155/6284778/ce2f4bca-b8fc-11e4-8564-b9a2bd4d284f.png)
Tkachenko Vlad

**Comment by DmitrySidorov** [comment]
Type of exception?

**Comment by DmitrySidorov** [comment]
Do not reproduced in 1.0.33.x
