### ISSUE TITLE
Неочевидная ошибка при установке

### ISSUE THREAD

**Issue by Kosenko-Yuriy** [olga-jane/prizm#1539]
![1](https://cloud.githubusercontent.com/assets/11027664/6284833/960e73f0-b8fd-11e4-813f-ae18cdacc87c.jpg)
при попытке названия "Master" выдает ошибку из котрой не очевидно что создание такого проекта - невозможно. Возможно стоит выводить иную ошибку, или зарание уведомлять пользователя о недоступности таких названий.

**Comment by gasty** [comment]
Бфло б хорошо, возможно уточнить, что ТОЛЬКО из цифр и букв:

![12](https://cloud.githubusercontent.com/assets/11043173/6284928/a9b8d750-b8fe-11e4-863e-3d2abfccd1bb.png)
