### ISSUE TITLE
Проблема с Наряд-заказом при создании новой трубы [Exception] [Mill] 1.0.32.9992

### ISSUE THREAD

**Issue by VladBekleneshev** [olga-jane/prizm#1543]
0)Завод->Новая труба
1)Сразу поставить курсор в поле "Наряд-заказ" и ввести число
2)Поставить курсор в другое поле - появится окно "Создать наряд заказ". Создать заказ с устаревшей датой.
![npipe](https://cloud.githubusercontent.com/assets/11027650/6285097/7df33a8c-b900-11e4-92b6-4b795552568b.JPG)

3)Нажимаем сохранить в 1й раз - ничего не происходит. Нажимаем 2й раз - исключение:
![npipe_exception](https://cloud.githubusercontent.com/assets/11027650/6285099/8009b9a4-b900-11e4-9fd4-9931171844a1.JPG)

Сведения:
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
NHibernate.StaleStateException: Batch update returned unexpected row count from update; actual row count: 0; expected: 1
   в NHibernate.AdoNet.Expectations.VerifyOutcomeBatched(Int32 expectedRowCount, Int32 rowCount)
   в NHibernate.AdoNet.SqlClientBatchingBatcher.DoExecuteBatch(IDbCommand ps)
   в NHibernate.AdoNet.AbstractBatcher.ExecuteBatchWithTiming(IDbCommand ps)
   в NHibernate.AdoNet.AbstractBatcher.ExecuteBatch()
   в NHibernate.Engine.ActionQueue.ExecuteActions(IList list)
   в NHibernate.Engine.ActionQueue.ExecuteActions()
   в NHibernate.Event.Default.AbstractFlushingEventListener.PerformExecutions(IEventSource session)
   в NHibernate.Event.Default.DefaultFlushEventListener.OnFlush(FlushEvent event)
   в NHibernate.Impl.SessionImpl.Flush()
   в NHibernate.Transaction.AdoTransaction.Commit()
   в Prizm.Data.DAL.Hibernate.AbstractHibernateRepository`2.Commit()
   в Prizm.Main.Forms.PipeMill.Purchase.SaveOrderCommand.Execute()
   в Prizm.Main.Forms.PipeMill.PurchaseOrderXtraForm.saveButton_Click(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)
   в DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   в DevExpress.XtraEditors.BaseControl.WndProc(Message& msg)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Prism.Program
    Версия сборки: 1.0.32.9992
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/Prism.Program.exe
----------------------------------------
Prism.Domain
    Версия сборки: 1.0.32.9992
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/Prism.Domain.DLL
----------------------------------------
log4net
    Версия сборки: 1.2.13.0
    Версия Win32: 1.2.13.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/log4net.DLL
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
DevExpress.XtraEditors.v14.2
    Версия сборки: 14.2.3.0
    Версия Win32: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/DevExpress.XtraEditors.v14.2.DLL
----------------------------------------
DevExpress.Utils.v14.2
    Версия сборки: 14.2.3.0
    Версия Win32: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/DevExpress.Utils.v14.2.DLL
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Prism.Data
    Версия сборки: 1.0.32.9992
    Версия Win32: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/Prism.Data.DLL
----------------------------------------
Ninject
    Версия сборки: 3.2.0.0
    Версия Win32: 3.2.2.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/Ninject.DLL
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
DevExpress.Data.v14.2
    Версия сборки: 14.2.3.0
    Версия Win32: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/DevExpress.Data.v14.2.DLL
----------------------------------------
NHibernate
    Версия сборки: 3.3.1.4000
    Версия Win32: 3.3.4.4000
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/NHibernate.DLL
----------------------------------------
FluentNHibernate
    Версия сборки: 1.4.0.0
    Версия Win32: 1.4.0.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/FluentNHibernate.DLL
----------------------------------------
System.Data
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Версия сборки: 0.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
DevExpress.XtraGrid.v14.2
    Версия сборки: 14.2.3.0
    Версия Win32: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/DevExpress.XtraGrid.v14.2.DLL
----------------------------------------
System.xml.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Xml.resources.dll
----------------------------------------
DevExpress.XtraBars.v14.2
    Версия сборки: 14.2.3.0
    Версия Win32: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/DevExpress.XtraBars.v14.2.DLL
----------------------------------------
DevExpress.XtraLayout.v14.2
    Версия сборки: 14.2.3.0
    Версия Win32: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/DevExpress.XtraLayout.v14.2.DLL
----------------------------------------
Microsoft.GeneratedCode
    Версия сборки: 1.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Iesi.Collections
    Версия сборки: 1.0.1.0
    Версия Win32: 3.2.0.4000
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/Iesi.Collections.DLL
----------------------------------------
System.Xml.Linq
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Transactions
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Numerics
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
DevExpress.Mvvm.v14.2
    Версия сборки: 14.2.3.0
    Версия Win32: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/DevExpress.Mvvm.v14.2.DLL
----------------------------------------
UIAutomationClient
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
PresentationCore
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
PresentationFramework
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
System.Xaml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
DevExpress.Mvvm.v14.2.DynamicTypes.15df5f44-3140-461b-851d-791efd6a4ba1
    Версия сборки: 0.0.0.0
    Версия Win32: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/DevExpress.Mvvm.v14.2.dll
----------------------------------------
SeamTypeProxyAssembly
    Версия сборки: 0.0.0.0
    Версия Win32: 3.3.4.4000
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/NHibernate.dll
----------------------------------------
CategoryProxyAssembly
    Версия сборки: 0.0.0.0
    Версия Win32: 3.3.4.4000
    CodeBase: file:///C:/Program%20Files/Prism/MillProject/NHibernate.dll
----------------------------------------
System.Design
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408 built by: FX451RTMLREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
System.Data.Linq
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.19408
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Linq.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.

**Comment by demmy** [comment]
Not confirmed on 1.0.32.1 (1.0.33.1) at 23/2/2015
