### ISSUE TITLE
Can't add an inspection to pipe

### ISSUE THREAD

**Issue by Jeanosis** [olga-jane/prizm#1546]
Can't add an inspection to pipe in Construction. "Add" and "Edit" buttons don't work.

Instruction(1.0.32.9992):
1. Open "Settings" menu
2. Select "Find pipes"
3. Open a pipe

Pic. 1
![image](https://cloud.githubusercontent.com/assets/11027096/6285143/eefce390-b900-11e4-9d5e-2eddd6eb0387.png)

Yefremov Stanislav

**Comment by demmy** [comment]
User can't add information or edit **shipped** pipe

**Comment by olga-jane** [comment]
not bug
