### ISSUE TITLE
I can save the same values v.1.0.32.9992

### ISSUE THREAD

**Issue by Stasplahtii** [olga-jane/prizm#1548]
[Construction]
Settings-Pipe
![image](https://cloud.githubusercontent.com/assets/11027688/6285218/eae463c2-b901-11e4-80dd-370d7f630d13.png)

Edit inspection operation 
![image](https://cloud.githubusercontent.com/assets/11027688/6285269/5e7db19e-b902-11e4-9d00-fb187e46ac55.png)

(Window's title name is "Add inspection operation " insted of "Edit inspection operation" )
Change code on one that has already created (for example "03") and save
![image](https://cloud.githubusercontent.com/assets/11027688/6285291/b486d002-b902-11e4-9b14-413855dbb097.png)
But it was saved ! 
![default](https://cloud.githubusercontent.com/assets/11027688/6285308/e1744108-b902-11e4-9742-7f0a44f54056.JPG)

**Comment by AleksMorozova** [comment]
same issue: Pipe inspection operations grid in settings: operation code must be unique. #994
