### ISSUE TITLE
Problem with add new components. [Construction] v 1.0.32.9992

### ISSUE THREAD

**Issue by TanyaPilipenko** [olga-jane/prizm#1551]
When I want to add new components that error.
![default](https://cloud.githubusercontent.com/assets/11027648/6285929/86843296-b90a-11e4-9c30-bbe34c2e70fd.jpg)

**Comment by DmitrySidorov** [comment]
Step by step scenario?
Type of exception?

**Comment by TanyaPilipenko** [comment]
I consistently introduce data to create a components.
And when I click "Save" generates an error.
