### ISSUE TITLE
Можно создать отрицательную катушку

### ISSUE THREAD

**Issue by Chifuyu** [olga-jane/prizm#1555]
Входной контроль и строительство
Катушки
Введите размер больше чем позволяет труба
Выводит ошибку
Нажмите ок и попробуйте стрелочками увеличить размер или уменьшить, но так что б он превышал размер трубы. Проделайте это несколько раз
При очередной попытке программа добавляет минус в размер катушки и можно сохранить без ошибок. 

![image](https://cloud.githubusercontent.com/assets/10714201/6286179/610b3700-b90d-11e4-81fc-637e3c6febe7.png)

Хоменко

**Comment by demmy** [comment]
Данная проблема возникает только при нулевой длине трубы, что в реальных условиях не возможно.

**Comment by Chifuyu** [comment]
оно само сбрасывает длину трубы на 0

![image](https://cloud.githubusercontent.com/assets/10714201/6335587/3070d47a-bba5-11e4-85c9-ba754fe4d63f.png)

![image](https://cloud.githubusercontent.com/assets/10714201/6335595/38d5bcb6-bba5-11e4-84ff-94b8a4647e7c.png)


![image](https://cloud.githubusercontent.com/assets/10714201/6335597/4104b810-bba5-11e4-8c52-b84bc72173be.png)


![image](https://cloud.githubusercontent.com/assets/10714201/6335604/52c7b390-bba5-11e4-8c20-22ecbecacea0.png)
