### ISSUE TITLE
Problem with settings. [Construction] v 1.0.32.9992

### ISSUE THREAD

**Issue by TanyaPilipenko** [olga-jane/prizm#1558]
Settings -> Pipe

![default](https://cloud.githubusercontent.com/assets/11027648/6286368/6d27dd34-b90f-11e4-859c-e587d1fc840e.jpg)
Даже если параметры трубы уникальное, то все-равно выдает ошибку.

**Comment by AleksMorozova** [comment]
already fixed - fix settings Validation #1565
