### ISSUE TITLE
Something break v1.0.32.9992 - checkboxes problem

### ISSUE THREAD

**Issue by KnightDanila** [olga-jane/prizm#1562]
1. Mill -> find Pipe -> Search
2. Double click on the pipe
![image](https://cloud.githubusercontent.com/assets/11027679/6286743/36b698b6-b924-11e4-806b-c1f953f60bd5.png)
3. Now, click on Edit
4. Click at here, twice or thrice
![image](https://cloud.githubusercontent.com/assets/11027679/6286747/3dfb4b1c-b924-11e4-8b39-5189f7971e67.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6286750/42cc5a5a-b924-11e4-9915-47436383865a.png)

Egoshkin Danila

**Comment by Chifuyu** [comment]
#1527
