### ISSUE TITLE
При обновлении версии  _1_0_32_9992 на версию _1_0_33_9990 контроль трубы не работает

### ISSUE THREAD

**Issue by Chifuyu** [olga-jane/prizm#1576]
При проходе контрольных операций вылетает ошибка

Завод
Создать трубу
Заполните поля
Перейдите во вкладку контрольных операций попробуйте отредактировать
Вылетает исключение

![image](https://cloud.githubusercontent.com/assets/10714201/6325108/ba3913f2-bb4b-11e4-9881-eeae9e7c5432.png)

Хоменко

**Comment by Chifuyu** [comment]
При обновлении любой версии происходит данная ошибка

**Comment by olga-jane** [comment]
to developer: Please, recheck on migration from our 32 to 33 version (installation packages can be found in share on my PC)

**Comment by olga-jane** [comment]
currently is not reproduced.
