### ISSUE TITLE
date is not displayed in Search Results v.1.0.33.9990

### ISSUE THREAD

**Issue by gasty** [olga-jane/prizm#1582]
1. Serch pipes
2. Input criteriaes
3. Click search
Result: search is done correctly, but in fields of dates in "Search Results" is empty.

![15](https://cloud.githubusercontent.com/assets/11043173/6325464/7a56653c-bb50-11e4-8841-d4cca3a55c15.png)

There was bag #1089. But there was probllem with result of search, but not with displaing datas.

Gorban

**Comment by AleksMorozova** [comment]
Columns for date were removed at update pipe search #1607
