### ISSUE TITLE
При просмотре трубы типоразмер - все 0 (для неактивного типоразмера)

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1593]
При просмотре трубы (дабл-клик на Поиск труб): типоразмер - все 0 (для неактивного в этот момент типоразмера). Нужны значения

**Comment by olga-jane** [comment]
solution is to discuss if there are some different non-standard ways

**Comment by DmitrySidorov** [comment]
The core of problem is not understandable.
Not active "PipeMillSizeType" does not contained in comboBox popUp, but displayed like current one. At the same time corresponding pipe have all inspection operation with all results.

**Comment by olga-jane** [comment]
CLIENT:

Я когда обнаружил этот баг действовал по другому алгоритму (сначала загнал в базу трубы одного типоразмера, потом другого и для безопасности оставлял активным только 1 типоразмер)

Короткий путь по шагам:
1.	Деактивируем один из типоразмеров, трубы этого типоразмера должны быть в БД
2.	Открываем Поиск труб
3.	Создаем список труб, чтобы в него попали трубы с деактивированным типоразмером
4.	Дабл-клик на одной из таких труб
5.	В открывшейся вкладке трубы выбираем Общие параметры трубы и там в группе Типоразмер поля  Длина, Диаметр, Толщина содержат нули. Остальные данные присутствуют, к ним замечаний нет.
