### ISSUE TITLE
между строками и колонками с информацией не должно быть пустых ячеек, объединение ячеек недопустимо

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1596]
Во всех отчетах при экспорте в Excel все данные по одной трубе должны обязательно выводится в 1 строку, между строками и колонками с информацией не должно быть пустых ячеек, объединение ячеек недопустимо. Вместо пиктограммы отметки в рамке в столбце Active надо использовать текст или 0/1

**Comment by AleksMorozova** [comment]
Problem with Loading (Shipped) report. It's difficult to organize label at subReport according to main report sizes
