### ISSUE TITLE
Отчеты v 1.0.33.9990

### ISSUE THREAD

**Issue by vlad0994** [olga-jane/prizm#1625]
Можно создать отчет с неправильными датой
![image](https://cloud.githubusercontent.com/assets/11043155/6367289/c9281d2e-bcd9-11e4-83fc-4530c9933eb3.png)
Ткаченко Влад.

**Comment by DmitrySidorov** [comment]
Is it contain any pipeline components?

**Comment by Chifuyu** [comment]
если дата стоит такая как на скрине, то трубы не появляются. но если дату переставить на правильную (1.02.2015 - 25.02.2015) то трубы появляются и с отчетом все впорядке

**Comment by DmitrySidorov** [comment]
Whats mean "wrong date"? Maybe, wrong date range?
It is assumed as normal behavior. Incorrect date range is user responsibility.

**Comment by Chifuyu** [comment]
Yes,  wrong date range.
