### ISSUE TITLE
Duplicate fields when export v.1.0.33.9990

### ISSUE THREAD

**Issue by Stasplahtii** [olga-jane/prizm#1626]
I exported three different files in [Constuction] program 
Mill->Find pipes
in the "Size type" field there are some duplicate values 
![default](https://cloud.githubusercontent.com/assets/11027688/6367563/4842f9dc-bcdd-11e4-9428-a99d7cf38df9.png)

**Comment by TanyaPilipenko** [comment]
+ Duplicate in settings.
[Master] - > Settings -> Project
![1](https://cloud.githubusercontent.com/assets/11027648/6368394/e6889604-bce4-11e4-9f01-c8c7ae74d379.jpg)
[Master] -> Settings -> Pipe
![2](https://cloud.githubusercontent.com/assets/11027648/6368412/219c75da-bce5-11e4-988a-21fa2523ebfa.jpg)

**Comment by AleksMorozova** [comment]
main issue: Pipe size parameters cloning #1481
