### ISSUE TITLE
непостоянность в логе по F4

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1640]
Есть какая-то непостоянность в логе по F4 при единообразной работе скрипта по заполнению Разрешений на отгрузку

![image](https://cloud.githubusercontent.com/assets/8179067/6388469/e403b274-bda2-11e4-8504-5700e36736b9.png)

**Comment by AleksMorozova** [comment]
We should save Release Note after shipping/unshipping because these operation modify ReleaseNote
