### ISSUE TITLE
Problem with settings pipe. [Mill] v 1.0.33.9990

### ISSUE THREAD

**Issue by TanyaPilipenko** [olga-jane/prizm#1642]
1) Завод
2) Поиск труб
3) Двойной клик на записи о трубе в БД
4) Поменять все контрольные операции на "Готов"
5) Нажать "Деактивировать трубу". Затем нажать "Нет".
6) Перейти на вкладку "Общие параметры трубы"
И вылетает ошибка.
![1234](https://cloud.githubusercontent.com/assets/11027648/6390349/451d47ee-bdb4-11e4-84a6-606bcc931711.jpg)
Details:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
NHibernate.LazyInitializationException: Initializing[Prizm.Domain.Entity.Mill.Weld#54345adb-f0c7-485e-923e-ee4c561b0922]-failed to lazily initialize a collection of role: Prizm.Domain.Entity.Mill.Weld.Welders, no session or session was closed
   at NHibernate.Collection.AbstractPersistentCollection.ThrowLazyInitializationException(String message)
   at NHibernate.Collection.AbstractPersistentCollection.ThrowLazyInitializationExceptionIfNotConnected()
   at NHibernate.Collection.AbstractPersistentCollection.Initialize(Boolean writing)
   at NHibernate.Collection.AbstractPersistentCollection.Read()
   at NHibernate.Collection.Generic.PersistentGenericBag`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Prizm.Main.Forms.PipeMill.NewEdit.MillPipeNewEditViewModel.FormatWeldersList(IList`1 welders)
   at Prizm.Main.Forms.PipeMill.NewEdit.MillPipeNewEditXtraForm.repositoryItemPopupWelders_CustomDisplayText(Object sender, CustomDisplayTextEventArgs e)
   at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseCustomDisplayText(CustomDisplayTextEventArgs e)
   at DevExpress.XtraEditors.Repository.RepositoryItemTextEdit.RaiseCustomDisplayText(CustomDisplayTextEventArgs e)
   at DevExpress.XtraEditors.Repository.RepositoryItem.RaiseCustomDisplayText(FormatInfo format, Object editValue, String displayText)
   at DevExpress.XtraEditors.Repository.RepositoryItem.GetDisplayText(FormatInfo format, Object editValue)
   at DevExpress.XtraEditors.Repository.RepositoryItemPopupContainerEdit.GetDisplayText(FormatInfo format, Object editValue)
   at DevExpress.XtraEditors.ViewInfo.BaseEditViewInfo.GetDisplayText()
   at DevExpress.XtraEditors.ViewInfo.TextEditViewInfo.GetDisplayText()
   at DevExpress.XtraEditors.ViewInfo.BaseEditViewInfo.OnEditValueChanged()
   at DevExpress.XtraEditors.ViewInfo.BaseEditViewInfo.set_EditValue(Object value)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.UpdateCellEditViewInfo(GridCellInfo cell, Point mousePos, Boolean canFastRecalculate, Boolean calc)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.CreateCellEditViewInfo(GridCellInfo cell, Boolean calc, Boolean allowCache)
   at DevExpress.XtraGrid.Views.Grid.ViewInfo.GridViewInfo.RequestCellEditViewInfo(GridCellInfo cell)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRegularRowCell(GridViewDrawArgs e, GridCellInfo ci)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRegularRow(GridViewDrawArgs e, GridDataRowInfo ri)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRow(GridViewDrawArgs e, GridRowInfo ri)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawRows(GridViewDrawArgs e)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.DrawContents(GridViewDrawArgs e)
   at DevExpress.XtraGrid.Views.Grid.Drawing.GridPainter.Draw(ViewDrawArgs ee)
   at DevExpress.XtraGrid.Views.Base.BaseView.Draw(GraphicsCache e)
   at DevExpress.XtraGrid.GridControl.OnPaint(PaintEventArgs e)
   at DevExpress.Utils.Drawing.ControlPaintHelper.PaintWithErrorHandling(PaintEventArgs paintEventArgs, Int32 layer)
   at DevExpress.Utils.Drawing.ControlPaintHelper.ProcessWMPaint(Message& m)
   at DevExpress.XtraGrid.GridControl.CheckProcessMsg(Message& m)
   at DevExpress.XtraGrid.GridControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Prism.Program
    Assembly Version: 1.0.33.9990
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/Prism.Program.exe
----------------------------------------
Prism.Domain
    Assembly Version: 1.0.33.9990
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/Prism.Domain.DLL
----------------------------------------
log4net
    Assembly Version: 1.2.13.0
    Win32 Version: 1.2.13.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/log4net.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
DevExpress.XtraEditors.v14.2
    Assembly Version: 14.2.3.0
    Win32 Version: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/DevExpress.XtraEditors.v14.2.DLL
----------------------------------------
DevExpress.Utils.v14.2
    Assembly Version: 14.2.3.0
    Win32 Version: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/DevExpress.Utils.v14.2.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Prism.Data
    Assembly Version: 1.0.33.9990
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/Prism.Data.DLL
----------------------------------------
Ninject
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.2.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/Ninject.DLL
----------------------------------------
DevExpress.Data.v14.2
    Assembly Version: 14.2.3.0
    Win32 Version: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/DevExpress.Data.v14.2.DLL
----------------------------------------
NHibernate
    Assembly Version: 3.3.1.4000
    Win32 Version: 3.3.4.4000
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/NHibernate.DLL
----------------------------------------
DevExpress.XtraGrid.v14.2
    Assembly Version: 14.2.3.0
    Win32 Version: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/DevExpress.XtraGrid.v14.2.DLL
----------------------------------------
FluentNHibernate
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/FluentNHibernate.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
DevExpress.XtraBars.v14.2
    Assembly Version: 14.2.3.0
    Win32 Version: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/DevExpress.XtraBars.v14.2.DLL
----------------------------------------
DevExpress.XtraLayout.v14.2
    Assembly Version: 14.2.3.0
    Win32 Version: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/DevExpress.XtraLayout.v14.2.DLL
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Iesi.Collections
    Assembly Version: 1.0.1.0
    Win32 Version: 3.2.0.4000
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/Iesi.Collections.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
DevExpress.Mvvm.v14.2
    Assembly Version: 14.2.3.0
    Win32 Version: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/DevExpress.Mvvm.v14.2.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
UIAutomationClient
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/UIAutomationClient/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationClient.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
DevExpress.Mvvm.v14.2.DynamicTypes.526387d1-53c7-4fce-8ca0-972e9568e3aa
    Assembly Version: 0.0.0.0
    Win32 Version: 14.2.3.0
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/DevExpress.Mvvm.v14.2.dll
----------------------------------------
SeamTypeProxyAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 3.3.4.4000
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/NHibernate.dll
----------------------------------------
CategoryProxyAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 3.3.4.4000
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/NHibernate.dll
----------------------------------------
InspectorCertificateTypeProxyAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 3.3.4.4000
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/NHibernate.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929 built by: FX45RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
System.Data.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.17929
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Data.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Data.Linq.dll
----------------------------------------
PlateProxyAssembly
    Assembly Version: 0.0.0.0
    Win32 Version: 3.3.4.4000
    CodeBase: file:///C:/Program%20Files/Prism/Factory133/NHibernate.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by AleksMorozova** [comment]
not reproduced
