### ISSUE TITLE
Settings forms give you visibility of changing settings when you are not allowed to.

### ISSUE THREAD

**Issue by IgorVskpsn** [olga-jane/prizm#1645]
Program version: 1.0.33.9990. Tested on Mill and Construction.

Steps to reprodece:
1. Go to Settings -> Roles and create a new role.
2. Select View Settings checkbox and deselect Settings edit checkbox.
3. Go to Settings -> Users and create a new user of role you've just created.
4. Restart the program and log in as the user you created on previous step.
5. Go to any settings form and try to change something.

You can change data in the form you've chosen until you switch to an another form. Then you cannot change any text field on any form as it should be. If you close the form, you'll get the standard dialog which proposes you to save changes. Those changes are not saved anyway, so the program works corectly. The error is only in allowing to change options on the first open settings form and pretending them to be stored.

Create a role.
![image](https://cloud.githubusercontent.com/assets/10723795/6391282/5bd02fde-bdbd-11e4-8237-f1a14570ac8c.png)

Create a user.
![image](https://cloud.githubusercontent.com/assets/10723795/6391299/95acb40c-bdbd-11e4-8aeb-7c5787e3f6dc.png)

Log in.
![image](https://cloud.githubusercontent.com/assets/10723795/6391308/bd7aefe4-bdbd-11e4-8113-fbcd04d63304.png)

Choose a parameter.
![image](https://cloud.githubusercontent.com/assets/10723795/6391336/f99baf2c-bdbd-11e4-9d84-e0f1126fc1b0.png)

Change it.
![image](https://cloud.githubusercontent.com/assets/10723795/6391344/1b4ef908-bdbe-11e4-88d2-886099ca4403.png)

Close the form.
![image](https://cloud.githubusercontent.com/assets/10723795/6391361/4e0a91ae-bdbe-11e4-8984-c4777dc50f9c.png)

Confirm saving of the cahnges.
![image](https://cloud.githubusercontent.com/assets/10723795/6391371/627adad6-bdbe-11e4-8275-7892dfcc25c4.png)

Do not wory, nothing's changed.
![image](https://cloud.githubusercontent.com/assets/10723795/6391397/91d3392c-bdbe-11e4-873a-8a52d522405d.png)

**Comment by olga-jane** [comment]
PRISM-26
