### ISSUE TITLE
Галочка "принять всё принудительно" при повторном импорте порции

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#1647]

**Comment by DmitrySidorov** [comment]
![untitled diagram 2](https://cloud.githubusercontent.com/assets/8365021/6431910/4006f5b6-c048-11e4-883a-81f81d517e2c.jpg)

**Comment by DmitrySidorov** [comment]
Additional information is needed:
Is it need to memorize how the duplicate numbers conflict was resolved  in the initial pipeline elements portion export.

**Comment by olga-jane** [comment]
decided not to change anything yet
