### ISSUE TITLE
Translate (some things are mixed up) v1.0.33.9990

### ISSUE THREAD

**Issue by KnightDanila** [olga-jane/prizm#1655]
It is in Russian version
click to save
![image](https://cloud.githubusercontent.com/assets/11027679/6404203/fefd15e8-be2e-11e4-8cfd-e733d2da79a6.png)
in Master
![image](https://cloud.githubusercontent.com/assets/11027679/6404210/0e4ed4c8-be2f-11e4-8b71-5ceed89824d1.png)
It is in English version
![image](https://cloud.githubusercontent.com/assets/11027679/6404218/2c88b198-be2f-11e4-8e91-be8c5086ea11.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404220/30123ce4-be2f-11e4-81fb-b995126425cd.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404223/34730bb0-be2f-11e4-8da9-f3beb44e1816.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404224/37337e70-be2f-11e4-9e58-6d7c0d56c00f.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404227/3d5589ce-be2f-11e4-97dc-91c59bb668a7.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404229/4014f988-be2f-11e4-8a2d-53374a6a2823.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404231/43f21b94-be2f-11e4-99f0-6377b2fec9fc.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404232/471e7ac4-be2f-11e4-9d73-8e3254b08856.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404233/4afa1ff4-be2f-11e4-938a-68901da4e604.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404235/4ddd12bc-be2f-11e4-9aed-46506d81590b.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404237/525a2a78-be2f-11e4-9243-149b5411fc1d.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404238/56520fa6-be2f-11e4-944d-8e210d1eeff9.png)

Egoshkin Danila

**Comment by olga-jane** [comment]
@AleksMorozova in 34 build - ONLY first "no resource" problem
