### ISSUE TITLE
Different names and other v1.0.33.9990

### ISSUE THREAD

**Issue by KnightDanila** [olga-jane/prizm#1656]
1. Different names
![image](https://cloud.githubusercontent.com/assets/11027679/6404262/a0f0f716-be2f-11e4-9df1-3c32ce2fcbce.png)
2. "Railcar number" repeated twice, but the last column must have name "Status" like in Russian version.
![image](https://cloud.githubusercontent.com/assets/11027679/6404265/a8891dfa-be2f-11e4-880c-25263ed41140.png)
3. Empty Space - what for?
![image](https://cloud.githubusercontent.com/assets/11027679/6404271/b070b186-be2f-11e4-9758-7c68eab106e4.png)
4. We can change a size of about
![image](https://cloud.githubusercontent.com/assets/11027679/6404283/b841ca26-be2f-11e4-84c1-359c6efc1596.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404284/bb76802e-be2f-11e4-950c-7dd4de735464.png)

Egoshkin Danila

**Comment by olga-jane** [comment]
prism-36
