### ISSUE TITLE
Custom AutoFilter v1.0.33.9990

### ISSUE THREAD

**Issue by KnightDanila** [olga-jane/prizm#1657]
1. Try to set "Условие"(it have Russian name in both versions)
![image](https://cloud.githubusercontent.com/assets/11027679/6404314/126f1ba2-be30-11e4-99b4-31c0bec0d4c6.png)
2. "Custom AutoFilter" - try to do something (it is also have some problems with translation)
![image](https://cloud.githubusercontent.com/assets/11027679/6404316/1b901466-be30-11e4-99ee-0be29be1b70a.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404319/1eabe4ea-be30-11e4-9b10-2aad676253ab.png)
3. Then we click on Quit

![image](https://cloud.githubusercontent.com/assets/11027679/6404326/274453da-be30-11e4-9788-e9ff126b849b.png)
4. If we click on some one of this buttons, we get different errors, like
![image](https://cloud.githubusercontent.com/assets/11027679/6404331/2eed83fe-be30-11e4-84c1-47ca80c808c9.png)
![image](https://cloud.githubusercontent.com/assets/11027679/6404332/325e5464-be30-11e4-8476-c49b12f4061c.png)
Egoshkin Danila

**Comment by olga-jane** [comment]
PRISM-30
