### ISSUE TITLE
Cannot Use Attachments or I did something wrong v1.0.33.9990

### ISSUE THREAD

**Issue by KnightDanila** [olga-jane/prizm#1658]
1. Open the Mill
2. Find some pipe 
3. Try to add Attachments

![image](https://cloud.githubusercontent.com/assets/11027679/6404601/3865062a-be33-11e4-8ccf-b84888b9ffa8.png)
4. Click on Eye

![image](https://cloud.githubusercontent.com/assets/11027679/6404604/3f8587cc-be33-11e4-90f4-89a0d3ef0078.png)

and how I can did it!? I just have a "Add file" and "Close"
5. Try to click on download icon (or maybe it is save icon), and save it in other folder (also try to save it in same folder), with same and other name, but always see it

![image](https://cloud.githubusercontent.com/assets/11027679/6404608/47a0caac-be33-11e4-860e-204f35b22949.png)

Egoshkin Danila

**Comment by olga-jane** [comment]
registered as https://olga-jane.myjetbrains.com/youtrack/issue/PRISM-11 
closed here
