### ISSUE TITLE
Empty fields Version v1.0.33.9990

### ISSUE THREAD

**Issue by vlad0994** [olga-jane/prizm#1659]
Если при создании новой трубы в имени нажать пробел то трубу можно будеть сохранить, тоже самое и для номера.

![image](https://cloud.githubusercontent.com/assets/11043155/6410526/12a05860-be81-11e4-8117-c164c5c3a520.png)

![image](https://cloud.githubusercontent.com/assets/11043155/6410451/78a612b8-be80-11e4-9321-fd6d6bcd5510.png)
Ткаченко Влад

**Comment by olga-jane** [comment]
We should not allow any spaces in identifiers (even terminal spaces). This should be solved on common level.
