### ISSUE TITLE
Save settings

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#177]
1) to save visual sizes (column width, window position etc)
2) to save something like "last entered date" for new pipe.

Some information about settings:
app.config is used for application settings, could not be modified by application in non-admin windows credentials
user.config is used for windows user settings, could be updated by application but applied to certain windows user

Please discuss before coding.

**Comment by demmy** [comment]
Implementation postponed because new devexpress component WorkspaceManager as yet unstable
