### ISSUE TITLE
Test Results records loss at pipe type size change

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#328]
Initial conditions: to have some inspection operations at 2 type sizes (settings/pipe).
create pipe. Set 1st type size. Go to inspection operations and make sure appropriate operations list is shown.
Save pipe.
Reopen pipe for editing.
Change type size. Go to inspection operations. List of inspection operations will change.
Save pipe.
Check DB records.
Problem: There are old TestResult records remain which will never be used or shown to user.

**Comment by olga-jane** [comment]
@AleksMorozova  please propose a solution

**Comment by AleksMorozova** [comment]
Old test result is used in Audit
