### ISSUE TITLE
In Settings IsModified doesn't work correctly 

### ISSUE THREAD

**Issue by AleksMorozova** [olga-jane/prizm#657]

**Comment by olga-jane** [comment]
Now edit mode is working on Settings form while initializing new row.
List of grids where edit mode is not working while in place editing:
Mill->new pipe: coatingHistory, weldingHistory, inspections
Components: componentParameters, inspectionHistoryGrid
Spools: inspectionHistoryGrid
On NewEditJoint form is already in edit mode while opening
Settings: plateManufacturerList, categoriesGrid, seemType, pipesSizeList, inspectionOperation, jointOperations, componentryTypeGridControl, gridControlInspectorsCertificates, gridControlUsers, gridControl1(roles).
Also on the all forms except Setting while initializing new row form does not go in edit mode
