### ISSUE TITLE
program opens the same entity twice. Should activate already opened.

### ISSUE THREAD

**Issue by ukrandruha** [olga-jane/prizm#690]
Please implement child form to be opened as (use existing abilities of ChildForm):
Settings: single screen (as is) (correct to typeof().Name instead of hardcoded string)
Search screens: single screens
Quick incoming inspection: single screen
Audit: single screen
System messages: single screen
Custom reports: single screen (leave // TODO comment)
Spools from main menu: single screen
All other reports: single screen

documents with single existing entities (by guids) should be opened once "per entity". Think about additional data structure in main form. discuss before coding.

**Comment by DmitrySidorov** [comment]
minus: Guid Id { get; }
plus: bool .....(Guid id)

**Comment by DmitrySidorov** [comment]
Separate responsibility of creation and opening child forms.
Redesign method of MainForm for opening/creation child forms.
