### ISSUE TITLE
Please review UI and make corrections

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#771]
1)
Grammar mistakes everywhere

2)
Set min sizes of buttons (basic MIN size as Сохранить for example)

3)
Unique yotkeys on forms (f.e. &Номер трубы). Every button of the form must have Hotkey, too.

4)
make Поиск accept button

5)
Recheck proper terms (in translation document)

**Comment by olga-jane** [comment]
is it this task finished?

**Comment by AleksMorozova** [comment]
I didn't recheck all proper terms (in translation document)
