### ISSUE TITLE
Reports: протяженность трубопровода и трассовка

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#772]
Please suggest:
- how reports will look.
- implementation details.

Please discuss before coding.
Coding should be done at least in 2 parts: each report separately.

**Comment by DmitrySidorov** [comment]
It is assumed that the first part of this task will include:
    1.1 implementation of the tracing algorithm
    1.2 tracing the pipeline from joint to joint and reporting

The second part of the task include:
    2.1 calculation the length of the pipeline between defining points
    2.2 the report on used parts between defining points

**Comment by DmitrySidorov** [comment]
Note for sub paragraph "2.2 the report on used parts between defining points" :
It is assumed: the Report at construction by "All used Parts" between kilometer post points gives ONLY corresponding parts with defined piket coordinates.
