### ISSUE TITLE
new Joint can't be opened

### ISSUE THREAD

**Issue by DmitrySidorov** [olga-jane/prizm#783]
Scenario:
1. Run "PRIZM"
2. Go to "Входной контроль и строительство" -> "Новый стык"

Result:
"An unhandled exception of type 'System.ArgumentException' occurred in System.Data.dll
Additional information: Column 'constructionStatus' does not belong to table ."

Expected Result:
Open New Joint creation

**Comment by olga-jane** [comment]
introduced by Reports Preview save time + SQLQueryString refactoring #781
