### ISSUE TITLE
Typesize parameters

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#791]
Client requested following typesize parameters:
- диаметр трубы
- толщину стенки трубы
- номинальную длину трубы
- тип шва

So following changes should be made:
- [x] Settings/Project/Mill
add grid "Виды сварочных швов" with seam types (без шва, спиральный, прямой are default values which should be seed by code (not by FillDb)). It should work the same way as inspection operations groups.

- [x] Settings/Pipe
make less the height of inspection operations grid.
Below, create control group "Дополнительные параметры выбранного типоразмера"
It will contain 4 parameters mentioned above.

- [x]  new/edit pipe
- Create new group Типоразмер and place it below Фактический размер. Make lower the line of bottom controls, for it (it has some space).
- Move diameter and thickness to Типоразмер. Add also edit "Длина" to Типоразмер
- make length, diameter and thickness read-only parameters and take them from typesize settings.
- so in Фактический размер will remain length (exact pipe parameter) and read-only calculable weight.

- [ ] CheckReadonly develop better solution taking into account editMode.

**Comment by AleksMorozova** [comment]
CheckReadonly rewrite in next commit
