### ISSUE TITLE
the Joint do not create after repeatedly click "Save / New" button

### ISSUE THREAD

**Issue by DmitrySidorov** [olga-jane/prizm#858]
Scenario:
1. Open "Входной контроль и строительство" -> "Создать стык"
2. Fill required fields (# joint1 connect pipe1 with pipe2 ) and click "Save / New" button 
3. Repeatedly Fill required fields (# joint2 connect pipe3 with pipe4 )
4. Click  "Save / New" or "Save" button
5. Reopen form "NewJoint"

Result:
The elements pipe1 and pipe2 are disconnected (it have the initial number of connector)

**Comment by olga-jane** [comment]
please discuss your solution before coding

**Comment by DmitrySidorov** [comment]
This bug have been fixed of its own accord after the merge
"joint cutting" #923 pull request
