### ISSUE TITLE
Every table in our Db should contain primary key

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#860]
Every table in our Db should contain primary key.
Please review tables. which tables doesn't contain PK? which of them require/doesn't require Guid as a PK?

**Comment by kapcia** [comment]
List of tables:
Audit - needs PK on id column
Coat - needs PK on id column
TestResult_Inspector - intermediary table to save many-to-many relationship, PK may be created on both colums
VersionInfo - doesn't require Guid as PK
Weld_Welder - intermediary table to save many-to-many relationship
WeldResult_Welder - intermediary table to save many-to-many relationship

**Comment by olga-jane** [comment]
VersionInfo - Guid (just in case).
All others - OK

**Comment by olga-jane** [comment]
(!) VersionInfo table is generated by fluent migrator and its script is not accessible
