### ISSUE TITLE
do not selected "All Welders"

### ISSUE THREAD

**Issue by DmitrySidorov** [olga-jane/prizm#870]
Scenario:
1. Open any form with welder choosing (for example NewPipeForm)
2. Set the date of welding
3. Open popup to welders set
4. Select all welders

Result:
An unhandled exception of type 'System.NullReferenceException' occurred in Prizm.Program.exe
Additional information: Object reference not set to an instance of an object.

There is same problem for inspectors

**Comment by AleksMorozova** [comment]
error if all welders or inspectors are active
