### ISSUE TITLE
Export/Import set flag "to export" in proper places (Hrs 6-, Due 17 Jan)

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#883]
Google document PRIZMA Design contains 2 diagrams in Data export/import section.
These diagrams show, when and at what conditions should be set the flag "to export".
DB column exists already.

Hours: up to 6
Due date: 17 January

**Comment by demmy** [comment]
eap, look please - 'Prizm.Domain.Entity.Mill.Pipe' does not contain a definition for 'ToExport'
