### ISSUE TITLE
Revising construction reports according to specified information

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#900]
PLease revise (i.e. check and discuss the complexity of changes, then implement) our standard construction reports according to specified information:
<pre>
1.	ОТЧЕТЫ ПО СТРОЙКЕ

1.1.	Отчет по трубам

Форма для вывода информации по параметрам трубы работает по принципу фильтрации 
данных из БД труб по параметрам:
•	Pipe # - номер трубы, по которой необходима информация
•	Diameter - диаметр трубы
•	Thickness - толщина стенки трубы
•	Cert# - номер акта приема-передачи трубы
•	Seam – тип заводского шва трубы

После нажатия кнопки Поиск, данные по результатам поиска выводятся в таблицу, где:
•	Pipe # - номер трубы
•	Length  - длина трубы
•	Diameter - диаметр трубы
•	Thickness - толщина стенки трубы
•	Seam – тип заводского шва трубы 
•	Grade  - тип стали
•	Cert# - номер акта приема-передачи трубы
•	Date – дата акта приема-передачи трубы
•	J #1 – номер сварного стыка №1 (если труба заварена)
•	J #2 – номер сварного стыка №2 (если труба заварена)

Таким образом, по запросу, можно выводить необходимую информацию, в разрезе
 вышеприведенных параметров.

1.2.	Отчет по сварке (по дате)

Форма вывода информации по сварке за определенную дату. В форме выбирается дата, по
 которой необходима информация и нажимается кнопка Поиск.
Кроме сварных стыков, в отчет по сварке также выводятся данные по сварке внутри линейных 
объектов (КУ, КПОУ, УЗРГ).
•	Date – дата сварки стыка
•	Joint # - номер стыка
•	Pipe #1, Pipe #2 – номера труб №1 и №2
•	Length #1, Length #2 – длины труб №1 и №2
•	NDT date – дата проведения НК (неразрушающий контроль)
•	NDT result - результат проведения НК 
•	NDT after repair - результат проведения НК после ремонта стыка
•	Insulation date – дата изоляции стыка

1.3.	Отчет по сварке участка между пикетами

Отчет по сварке между пикетами выдает информацию по сварке линейных труб между
 заданными пикетами ПК старт и ПК финиш
Информация выводится в таблицу со следующими колонками:
•	Joint (стык)
•	Welding date (дата сварки стыка)
•	Pipe #1 (номер трубы 1)
•	Length #1 (длина трубы 1)
•	Parameter 1 (параметры трубы 1 – диаметр Х толщина стенки/тип заводского шва трубы)
•	Pipe #2 (номер трубы 2)
•	Length #2 (длина трубы 2)
•	Parameter 2 (параметры трубы 2 – диаметр Х толщина стенки/тип заводского шва трубы)

В нижней части формы посчитывается суммарное количество:
•	Joints – стыков в заданном диапазоне
•	Pipes -  труб в заданном диапазоне
•	Spools - катушек в заданном диапазоне
•	Length – общая длина трубопровода в заданном диапазоне
</pre>

**Comment by DmitrySidorov** [comment]
It is assumed that the problem will be solved in three steps:
part 1. - "Отчет по сварке участка между пикетами"
part 2. - "Отчет по трубам"
part 3. - "Отчет по сварке (по дате)"

**Comment by DmitrySidorov** [comment]
remains to determine the points:

1.1.    Отчет по трубам (вопросы по проекту PRIZMA No 124)
• Cert# - номер акта приема-передачи трубы
• Date – дата акта приема-передачи трубы

1.2.    Отчет по сварке (по дате)
• NDT date – дата проведения НК (неразрушающий контроль)
• NDT result - результат проведения НК 
• NDT after repair - результат проведения НК после ремонта стыка
• Insulation date – дата изоляции стыка
