### ISSUE TITLE
Настройки-проект, если переключить на вкладку труба появляется * [29] - bug?

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#937]
Настройки-проект, если переключить на вкладку труба появляется признак внесения изменений (*) и при закрытии просит о сохранении.

requires investigation

**Comment by demmy** [comment]
20/1/15 Master:
> Date:		14 hours ago (19/1/15 19:38:13 )
> Commit hash:	ce28710860b3faf5af264d50ecaa9964b2aec079

**Can not reproduce**
