### ISSUE TITLE
Settings / checkboxes save and validation [24] [25] - bugs?

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#938]
1)
Настройки-изменения чек-боксов не сохраняются, в логе по Ф4 нет сообщений, пока не изменишь какое-либо числовое значение и сохранишь. После этого работает нормально

2)
Настройки-труба-параметры типоразмера индикация ошибки и балон Не соответствует маске, если перед этим нажать Сохранить, которое не срабатывает (предыдущая проблема)

requires investigation

**Comment by DmitrySidorov** [comment]
The first part (1) is not reproduced in initial form. The Settings do not saved if the "Settings->Pipe" tab has'n had visits at first time: the Error window "Неверный формат данных"

**Comment by DmitrySidorov** [comment]
Extension for second part (2): the "Толщина стенки" in "Настройки-труба-параметры типоразмера" can not be entered as float, but should be float.

**Comment by olga-jane** [comment]
postponed: - some validation issues were fixed on settings; - waiting for correct Settings seeding.

**Comment by olga-jane** [comment]
please recheck if reproduces

**Comment by DmitrySidorov** [comment]
not reproduced in current version: setup_prism_2015_01_24 (20.05)
