### ISSUE TITLE
контроль последовательности файлов экспортируемых данных

### ISSUE THREAD

**Issue by olga-jane** [olga-jane/prizm#975]
в протоколе обмена нужно предусмотреть контроль последовательности файлов экспортируемых данных, т. е. каждый файл экспорта включает номер и если мастер не имеет данных из предыдущего файла, то импорт информации отклоняется и диагностируется количество (или номера) недостающих файлов

ps. numbering is per mill

**Comment by kapcia** [comment]
TODO: 
While creating data for export create sequence of portions and add sequence number to data manifest.
While importing data check the sequence number for importing project and if sequence is broken - show the workstation name/mill name and numbers of portions that are present and missing. (maybe in read-only text edit)
In db: add to portion table import\export flag, portion number (sequence)
