### ISSUE TITLE
Control operation groups test result: error message while saving project with a new group.

### ISSUE THREAD

**Issue by StaceyN** [olga-jane/prizm#991]
Step to reproduce:
1.Open tools 
2.Project
3. Add new item to " Группы котрольных операций".
4. Press "Save".
Expected result:
Project saved.
Actual result:
Message: "Error: check values."

The same error occures whlile saving project with new item in "Типы сварочных швов":

Step to reproduce:
1.Open tools 
2.Project
3. Add new item to "Типы сварочных швов".
4. Press "Save".
Expected result:
Project saved.
Actual result:
Message: "Error: check values."

 by Necheporenko Anastacia

**Comment by olga-jane** [comment]
requires investigation: validation should remain, in some cases (duplicate group name, etc)

**Comment by AleksMorozova** [comment]
already fixed - fix settings Validation #1565
