### ISSUE TITLE
Pipe inspection operations grid in settings: operation code must be unique.

### ISSUE THREAD

**Issue by StaceyN** [olga-jane/prizm#994]
Step to reproduce:
1. Open tools
2. Pipe
3. Add a new item to "Список контрольных операций" with code that exists in the list.
4. Press "Save".
Expected result:
Worning message and window don't close
Actual result:
Pipe saved.   

by Necheporenko Anastacia

**Comment by olga-jane** [comment]
code should be not duplicated only in case previous operation doesn't have the result

**Comment by olga-jane** [comment]
testing failed. It is possible to create duplicate operation code. moved to next build.
