### ISSUE TITLE
Duplicate value at Settings

### ISSUE THREAD

**Issue by KhabarlakKonstantin** [olga-jane/prizm#996]
Steps to reproduce:
1. Open the app
2. Go to "Настройки" -> "Комплектующие"
3. Add new connector

Expected result: duplicate and empty "Тип комлектующего" are not allowed
Actual result: you can create duplicate and empty "Тип комлектующего" and successfully save it.

**Comment by olga-jane** [comment]
@AleksMorozova  pleaes recheck if this is already fixed (reference here these issues)
